"""Backtest_Seeder — give the Deep Quant agent a track record on day one.

Phase 2.5 of the trading-edge roadmap. The live Trade_Journal (journal.py) only
learns as real trades accumulate and resolve, which means the agent's
`get_trade_performance` is empty until then. This seeder replays HISTORICAL
candles through a set of deterministic, rule-based setups and scores them with
the SAME conservative outcome logic the live journal uses, then writes the
resolved trades into the journal tagged ``source='backtest'``.

Why this is honest and useful:
  * The seeded trades are tagged with the SAME setup fingerprint
    (direction / macro alignment / predictive agreement / value-area location)
    as live LLM decisions, so per-setup statistics are directly comparable and
    give the agent a meaningful PRIOR on which setup *types* historically work.
  * Scoring uses the same worst-case fill assumption (a candle that straddles
    both stop and target counts as a loss), so the prior never flatters itself.
  * Seeded rows carry ``source='backtest'`` so they are always distinguishable
    from — and purgeable independently of — live trades.

IMPORTANT CAVEAT (surfaced to the user): the seeder's setups are generated by
simple deterministic RULES, not by the LLM agent. So the prior reflects how a
*setup type* behaves historically, not how this specific model would trade. It
is a starting calibration, not ground truth for the agent's own edge — live
trades gradually dominate the statistics.

Usage:
    python backtest.py --symbol RELIANCE --timeframe 15m --limit 3000
    python backtest.py --symbol RELIANCE --timeframe 1d --candles-file hist.json
    python backtest.py --symbol RELIANCE --timeframe 15m --dry-run   # no DB writes
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass, field
from typing import List, Optional

import httpx

import journal
# Reuse the AUTHORITATIVE volume-profile math and EMA helper so seeded levels
# match what the live agent and the UI compute.
from tools import _compute_volume_profile, calculate_ema

RUST_SERVER_URL = "http://localhost:8084"
# QuestDB HTTP query endpoint — the historical archive. Reading candles here lets
# the seeder pull real history WITHOUT the Tauri desktop app / Rust tool server
# running; only QuestDB (docker-compose) needs to be up.
QUESTDB_HTTP_URL = os.getenv("QUESTDB_HTTP_URL", "http://127.0.0.1:9000")

# Timeframes stored in the daily `historical_candles` table; everything else is
# read from `historical_intraday` filtered by its `timeframe` column.
_DAILY_TIMEFRAMES = {"1d", "d", "day", "1day", "1w", "1week", "week", "daily"}


# ── Configuration ─────────────────────────────────────────────────────────────

@dataclass
class BacktestConfig:
    lookback: int = 120           # bars of context the rules "see" per decision
    ema_fast: int = 9
    ema_slow: int = 21
    atr_period: int = 14
    ols_window: int = 20          # bars used for the predictive-slope proxy
    atr_stop_mult: float = 1.5    # stop distance = 1.5 x ATR (matches validator)
    risk_reward: float = 2.0      # target distance = RR x stop (matches validator)
    cooldown_bars: int = 5        # min bars between successive signals
    max_horizon_bars: int = 200   # give a trade this many bars to resolve
    profile_rows: int = 24
    value_area_percent: float = 70.0
    record_unresolved: bool = False  # skip trades that never hit stop/target


def _is_num(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)


# ── Indicator helpers (deterministic, pure) ──────────────────────────────────

def _atr(candles: List[dict], period: int) -> float:
    """Average True Range over the last ``period`` bars of ``candles``."""
    trs = []
    for i in range(1, len(candles)):
        h, l = candles[i].get("high"), candles[i].get("low")
        pc = candles[i - 1].get("close")
        if not (_is_num(h) and _is_num(l) and _is_num(pc)):
            continue
        trs.append(max(h - l, abs(h - pc), abs(l - pc)))
    if not trs:
        return 0.0
    window = trs[-period:] if len(trs) >= period else trs
    return sum(window) / len(window)


def _ols_slope(values: List[float]) -> float:
    """Least-squares slope of ``values`` against their index (predictive proxy)."""
    n = len(values)
    if n < 2:
        return 0.0
    xs = list(range(n))
    mx = sum(xs) / n
    my = sum(values) / n
    num = sum((xs[i] - mx) * (values[i] - my) for i in range(n))
    den = sum((xs[i] - mx) ** 2 for i in range(n))
    return num / den if den else 0.0


# ── Signal construction ───────────────────────────────────────────────────────

def _macro_conflict_str(action: str, bias: str) -> str:
    """Mirror graph.py's macro-trend-conflict phrasing so tagging matches."""
    opposes = (action == "BUY" and bias == "Bearish") or (action == "SELL" and bias == "Bullish")
    if opposes:
        return f"MACRO CONFLICT: {action} opposes the 1D trend bias ({bias})."
    return f"Aligned with the 1D trend bias ({bias})."


def _predictive_conflict_str(action: str, slope: float) -> str:
    """Mirror graph.py's predictive-conflict phrasing so tagging matches."""
    if slope > 0:
        proj = "Up"
    elif slope < 0:
        proj = "Down"
    else:
        proj = "Flat"
    agent = "Up" if action == "BUY" else "Down"
    if proj == "Flat":
        return f"Predictive projection is {proj} (source: ols_slope); no directional conflict."
    if {proj, agent} == {"Up", "Down"}:
        return f"CONFLICT: predictive projection is {proj} (source: ols_slope) but the trade bias is {agent}."
    return f"No predictive conflict: projection {proj} aligns with trade bias {agent} (source: ols_slope)."


def _build_decision(action: str, entry: float, atr: float, bias: str, slope: float,
                    vp: dict, created_at: float, cfg: BacktestConfig) -> Optional[dict]:
    """Construct a journal-shaped decision with validator-passing levels.

    Levels are set so stop distance == ``atr_stop_mult x ATR`` and reward ==
    ``risk_reward x`` risk, i.e. they always satisfy the live Trade_Validator
    (stop >= 1.5x ATR, RR >= 1:2) — the same bar the live agent must clear.
    """
    if not (_is_num(entry) and _is_num(atr)) or atr <= 0:
        return None
    risk = cfg.atr_stop_mult * atr
    reward = cfg.risk_reward * risk
    if action == "BUY":
        stop_loss = entry - risk
        take_profit = entry + reward
    else:  # SELL
        stop_loss = entry + risk
        take_profit = entry - reward

    return {
        "action": action,
        "conviction_score": 60,
        "entry": round(entry, 4),
        "stop_loss": round(stop_loss, 4),
        "take_profit": round(take_profit, 4),
        "atr_14": round(atr, 4),
        "created_at": created_at,
        "source": "backtest",
        "defensibility": {
            "risk_reward": round(reward / risk, 4) if risk > 0 else None,
            "macro_trend_conflict": _macro_conflict_str(action, bias),
            "predictive_conflict": _predictive_conflict_str(action, slope),
            "volume_profile": {
                "poc": vp.get("poc"),
                "vah": vp.get("vah"),
                "val": vp.get("val"),
                "price_vs_value_area": vp.get("price_vs_value_area"),
            },
        },
    }


def _signal_for_bar(window: List[dict], created_at: float, cfg: BacktestConfig) -> Optional[dict]:
    """Apply the deterministic rule set to a window and return a decision or None.

    Rules (priority order):
      A) Trend pullback (aligned): macro bullish + price at/below Value-Area Low
         → BUY; macro bearish + price at/above Value-Area High → SELL.
      B) Over-extension fade (counter-trend): price stretched well beyond the
         value area against an opposing macro → fade it (produces macro:against
         samples so the prior learns counter-trend setups are riskier).
    """
    closes = [c.get("close") for c in window if _is_num(c.get("close"))]
    if len(closes) < max(cfg.ema_slow, cfg.ols_window) + 1:
        return None

    ema_fast = calculate_ema(closes, cfg.ema_fast)
    ema_slow = calculate_ema(closes, cfg.ema_slow)
    if not (_is_num(ema_fast) and _is_num(ema_slow)) or ema_fast == ema_slow:
        return None
    bias = "Bullish" if ema_fast > ema_slow else "Bearish"

    atr = _atr(window, cfg.atr_period)
    if atr <= 0:
        return None
    slope = _ols_slope(closes[-cfg.ols_window:])

    vp = _compute_volume_profile(window, rows=cfg.profile_rows, value_area_percent=cfg.value_area_percent)
    vah, val = vp.get("vah"), vp.get("val")
    if not (_is_num(vah) and _is_num(val)):
        return None

    entry = closes[-1]

    # ── Rule A: trend-aligned pullback to the value-area edge ────────────────
    if bias == "Bullish" and entry <= val + 0.25 * atr:
        return _build_decision("BUY", entry, atr, bias, slope, vp, created_at, cfg)
    if bias == "Bearish" and entry >= vah - 0.25 * atr:
        return _build_decision("SELL", entry, atr, bias, slope, vp, created_at, cfg)

    # ── Rule B: counter-trend fade of an over-extension beyond value ─────────
    if bias == "Bullish" and entry > vah + 1.0 * atr:
        return _build_decision("SELL", entry, atr, bias, slope, vp, created_at, cfg)
    if bias == "Bearish" and entry < val - 1.0 * atr:
        return _build_decision("BUY", entry, atr, bias, slope, vp, created_at, cfg)

    return None


# ── Scoring against future candles (mirrors journal._score_one) ───────────────

def _score_signal(decision: dict, future: List[dict], cfg: BacktestConfig):
    """Score a decision against the bars that follow it.

    Returns (status, outcome_price, outcome_at_seconds, r_multiple) or None when
    there are no future bars at all. Worst-case: a bar touching both levels is a
    loss. A trade that resolves neither within ``max_horizon_bars`` is expired.
    """
    action = decision["action"]
    entry = decision["entry"]
    sl = decision["stop_loss"]
    tp = decision["take_profit"]
    risk = abs(entry - sl)
    if risk <= 0:
        return None
    rr = abs(tp - entry) / risk

    horizon = future[: cfg.max_horizon_bars]
    if not horizon:
        return None

    last_ts = None
    for c in horizon:
        hi, lo, ts = c.get("high"), c.get("low"), c.get("timestamp_ms")
        if not (_is_num(hi) and _is_num(lo)):
            continue
        last_ts = ts if _is_num(ts) else last_ts
        out_at = (ts / 1000.0) if _is_num(ts) else None
        hit_tp = hi >= tp if action == "BUY" else lo <= tp
        hit_sl = lo <= sl if action == "BUY" else hi >= sl
        if hit_sl and hit_tp:
            return "loss", sl, out_at, -1.0
        if hit_tp:
            return "win", tp, out_at, round(rr, 4)
        if hit_sl:
            return "loss", sl, out_at, -1.0

    return "expired", None, (last_ts / 1000.0 if _is_num(last_ts) else None), None


# ── Orchestration ─────────────────────────────────────────────────────────────

def generate_and_score(candles: List[dict], symbol: str, timeframe: str,
                       cfg: BacktestConfig) -> List[dict]:
    """Walk the candle history, emit rule-based signals, and score each one.

    Returns a list of result records: {decision, status, outcome_price,
    outcome_at, r_multiple}. Pure given the candle data (no DB / network).
    """
    results: List[dict] = []
    n = len(candles)
    if n < cfg.lookback + 2:
        return results

    cooldown_until = -1
    for i in range(cfg.lookback - 1, n - 1):
        if i < cooldown_until:
            continue
        window = candles[i - cfg.lookback + 1: i + 1]
        ts = candles[i].get("timestamp_ms")
        created_at = (ts / 1000.0) if _is_num(ts) else 0.0
        decision = _signal_for_bar(window, created_at, cfg)
        if decision is None:
            continue
        scored = _score_signal(decision, candles[i + 1:], cfg)
        if scored is None:
            continue
        status, out_price, out_at, r_mult = scored
        if status == "expired" and not cfg.record_unresolved:
            cooldown_until = i + cfg.cooldown_bars
            continue
        results.append({
            "decision": decision,
            "status": status,
            "outcome_price": out_price,
            "outcome_at": out_at,
            "r_multiple": r_mult,
        })
        cooldown_until = i + cfg.cooldown_bars
    return results


def _fetch_candles(symbol: str, timeframe: str, limit: int) -> List[dict]:
    r = httpx.post(
        f"{RUST_SERVER_URL}/tools/get_candles",
        json={"symbol": symbol, "timeframe": timeframe, "limit": limit},
        timeout=20.0,
    )
    r.raise_for_status()
    data = r.json()
    if not isinstance(data, list):
        raise RuntimeError(f"Unexpected candle payload: {type(data).__name__}")
    return data


def _fetch_candles_questdb(symbol: str, timeframe: str, limit: int) -> List[dict]:
    """Read historical candles directly from QuestDB's HTTP query API.

    Daily/weekly timeframes come from ``historical_candles``; all other (intraday)
    timeframes from ``historical_intraday`` filtered by its ``timeframe`` column.
    ``CAST(ts AS LONG)`` yields microseconds since epoch (QuestDB's native unit),
    which we convert to the milliseconds the rest of the pipeline expects.
    ``ORDER BY ts LIMIT -N`` returns the most recent N rows in ascending order.
    """
    sym = symbol.replace("'", "''")  # escape for the SQL string literal
    tf = (timeframe or "").strip().lower()
    if tf in _DAILY_TIMEFRAMES:
        query = (
            "SELECT CAST(ts AS LONG) AS ts_us, open, high, low, close, volume "
            f"FROM historical_candles WHERE symbol='{sym}' ORDER BY ts LIMIT -{int(limit)}"
        )
    else:
        tf_lit = timeframe.replace("'", "''")
        query = (
            "SELECT CAST(ts AS LONG) AS ts_us, open, high, low, close, volume "
            f"FROM historical_intraday WHERE symbol='{sym}' AND timeframe='{tf_lit}' "
            f"ORDER BY ts LIMIT -{int(limit)}"
        )

    r = httpx.get(f"{QUESTDB_HTTP_URL}/exec", params={"query": query}, timeout=30.0)
    r.raise_for_status()
    body = r.json()
    if isinstance(body, dict) and body.get("error"):
        raise RuntimeError(f"QuestDB query error: {body.get('error')} (table may not exist or be empty)")
    dataset = body.get("dataset") if isinstance(body, dict) else None
    if not dataset:
        raise RuntimeError(
            f"QuestDB returned no rows for {symbol}/{timeframe}. "
            f"Has historical data been loaded for this symbol/timeframe?"
        )

    candles: List[dict] = []
    for row in dataset:
        if len(row) < 6 or row[0] is None:
            continue
        candles.append({
            "timestamp_ms": float(row[0]) / 1000.0,  # micros -> millis
            "open": row[1], "high": row[2], "low": row[3],
            "close": row[4], "volume": row[5] if row[5] is not None else 0.0,
        })
    return candles


def _resolve_candles(symbol: str, timeframe: str, limit: int, source: str) -> List[dict]:
    """Resolve candles from the requested source.

    ``auto`` (default) tries QuestDB first (works without the Tauri app), then
    falls back to the Rust tool server. ``questdb`` / ``server`` force one path.
    """
    if source == "questdb":
        return _fetch_candles_questdb(symbol, timeframe, limit)
    if source == "server":
        return _fetch_candles(symbol, timeframe, limit)
    # auto
    try:
        return _fetch_candles_questdb(symbol, timeframe, limit)
    except Exception as qe:
        print(f"[Backtest_Seeder] QuestDB source unavailable ({qe}); trying Rust tool server...")
        return _fetch_candles(symbol, timeframe, limit)


def _load_candles_file(path: str) -> List[dict]:
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    if isinstance(data, dict) and isinstance(data.get("candles"), list):
        data = data["candles"]
    if not isinstance(data, list):
        raise RuntimeError("candles file must be a JSON list (or {\"candles\": [...]})")
    return data


def seed(symbol: str, timeframe: str, limit: int = 3000,
         candles: Optional[List[dict]] = None, cfg: Optional[BacktestConfig] = None,
         purge_first: bool = True, dry_run: bool = False, source: str = "auto") -> dict:
    """Generate, score, and (unless dry_run) write backtest trades to the journal.

    Returns a summary dict with the number of trades by outcome plus the
    resulting backtest-only stats from the journal.
    """
    cfg = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    results = generate_and_score(candles, symbol, timeframe, cfg)
    wins = sum(1 for r in results if r["status"] == "win")
    losses = sum(1 for r in results if r["status"] == "loss")
    expired = sum(1 for r in results if r["status"] == "expired")

    summary = {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "signals_scored": len(results),
        "wins": wins,
        "losses": losses,
        "expired": expired,
        "dry_run": dry_run,
    }

    if dry_run:
        summary["note"] = "dry-run: no journal writes performed"
        return summary

    if purge_first:
        removed = journal.purge(source="backtest", symbol=symbol)
        summary["purged_existing_backtest"] = removed

    written = 0
    for r in results:
        rid = journal.record_backtest_trade(
            r["decision"], symbol=symbol, timeframe=timeframe,
            status=r["status"], outcome_price=r["outcome_price"],
            outcome_at=r["outcome_at"], r_multiple=r["r_multiple"],
        )
        if rid is not None:
            written += 1
    summary["written"] = written
    summary["stats"] = journal.get_stats(symbol=symbol, source="backtest")
    return summary


# ── Discovery & batch seeding ─────────────────────────────────────────────────

def discover_symbols(source: str = "questdb") -> List[str]:
    """Return every symbol present in the QuestDB archive (daily ∪ intraday)."""
    symbols = set()
    for table in ("historical_candles", "historical_intraday"):
        try:
            r = httpx.get(
                f"{QUESTDB_HTTP_URL}/exec",
                params={"query": f"SELECT DISTINCT symbol FROM {table}"},
                timeout=15.0,
            )
            r.raise_for_status()
            body = r.json()
            for row in body.get("dataset", []) or []:
                if row and row[0]:
                    symbols.add(row[0])
        except Exception as e:
            print(f"[Backtest_Seeder] symbol discovery from {table} failed: {e}")
    return sorted(symbols)


def discover_intraday_timeframes() -> List[str]:
    """Return the distinct intraday timeframe labels stored in QuestDB."""
    try:
        r = httpx.get(
            f"{QUESTDB_HTTP_URL}/exec",
            params={"query": "SELECT DISTINCT timeframe FROM historical_intraday"},
            timeout=15.0,
        )
        r.raise_for_status()
        body = r.json()
        tfs = [row[0] for row in body.get("dataset", []) or [] if row and row[0]]
        return sorted(tfs)
    except Exception as e:
        print(f"[Backtest_Seeder] intraday timeframe discovery failed: {e}")
        return []


def seed_batch(symbols: List[str], timeframes: List[str], limit: int = 3000,
               cfg: Optional[BacktestConfig] = None, purge_first: bool = True,
               dry_run: bool = False, source: str = "auto") -> dict:
    """Seed every (symbol × timeframe) combination.

    Purges existing backtest rows ONCE per symbol (covering all its timeframes)
    before seeding, so re-runs stay idempotent without wiping earlier timeframes
    mid-batch. Each cell is isolated: a failure (e.g. no data for that
    symbol/timeframe) is recorded and the batch continues.
    """
    cfg = cfg or BacktestConfig()
    cells = []
    totals = {"signals_scored": 0, "wins": 0, "losses": 0, "written": 0, "errors": 0}

    for sym in symbols:
        if purge_first and not dry_run:
            removed = journal.purge(source="backtest", symbol=sym)
            if removed:
                print(f"[Backtest_Seeder] purged {removed} existing backtest row(s) for {sym}.")
        for tf in timeframes:
            try:
                res = seed(sym, tf, limit=limit, cfg=cfg, purge_first=False,
                           dry_run=dry_run, source=source)
                cells.append({
                    "symbol": sym, "timeframe": tf,
                    "signals_scored": res.get("signals_scored", 0),
                    "wins": res.get("wins", 0), "losses": res.get("losses", 0),
                    "written": res.get("written", 0),
                })
                totals["signals_scored"] += res.get("signals_scored", 0)
                totals["wins"] += res.get("wins", 0)
                totals["losses"] += res.get("losses", 0)
                totals["written"] += res.get("written", 0)
                print(f"[Backtest_Seeder] {sym}/{tf}: {res.get('signals_scored',0)} scored "
                      f"({res.get('wins',0)}W/{res.get('losses',0)}L), {res.get('written',0)} written.")
            except Exception as e:
                totals["errors"] += 1
                cells.append({"symbol": sym, "timeframe": tf, "error": str(e)})
                print(f"[Backtest_Seeder] {sym}/{tf}: SKIPPED ({e})")

    scored = totals["wins"] + totals["losses"]
    return {
        "symbols": len(symbols),
        "timeframes": timeframes,
        "totals": totals,
        "overall_win_rate": round(totals["wins"] / scored, 4) if scored else None,
        "dry_run": dry_run,
        "cells": cells,
    }


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(description="Seed the Trade_Journal from historical candles.")
    p.add_argument("--symbol", default=None, help="Trading symbol, e.g. RELIANCE (omit with --all-symbols)")
    p.add_argument("--all-symbols", action="store_true", help="Seed every symbol found in the QuestDB archive")
    p.add_argument("--timeframe", default="1d",
                   help="Timeframe(s), comma-separated (e.g. '1d,15m,1h'). Default 1d")
    p.add_argument("--all-timeframes", action="store_true",
                   help="Seed 1d plus every intraday timeframe present in QuestDB")
    p.add_argument("--limit", type=int, default=3000, help="Candles to fetch per symbol/timeframe")
    p.add_argument("--source", choices=["auto", "questdb", "server"], default="auto",
                   help="Candle source: auto (QuestDB then tool server), questdb, or server")
    p.add_argument("--candles-file", default=None,
                   help="Load candles from a JSON file (single symbol/timeframe only)")
    p.add_argument("--no-purge", action="store_true", help="Do not purge existing backtest rows first")
    p.add_argument("--dry-run", action="store_true", help="Compute and print stats without writing to the journal")

    # ── Rule tuning knobs ────────────────────────────────────────────────────
    p.add_argument("--rr", type=float, default=None, help="Risk:Reward multiple (target = RR x stop). Default 2.0")
    p.add_argument("--atr-mult", type=float, default=None, help="Stop distance as a multiple of ATR. Default 1.5")
    p.add_argument("--horizon", type=int, default=None, help="Max bars to let a trade resolve. Default 200")
    p.add_argument("--cooldown", type=int, default=None, help="Min bars between successive signals. Default 5")
    p.add_argument("--lookback", type=int, default=None, help="Bars of context per decision. Default 120")
    p.add_argument("--record-expired", action="store_true",
                   help="Also record trades that never hit stop/target (as 'expired')")
    args = p.parse_args()

    # Build the config from any provided knobs (unset → dataclass defaults).
    cfg = BacktestConfig()
    if args.rr is not None:
        cfg.risk_reward = args.rr
    if args.atr_mult is not None:
        cfg.atr_stop_mult = args.atr_mult
    if args.horizon is not None:
        cfg.max_horizon_bars = args.horizon
    if args.cooldown is not None:
        cfg.cooldown_bars = args.cooldown
    if args.lookback is not None:
        cfg.lookback = args.lookback
    if args.record_expired:
        cfg.record_unresolved = True

    # Resolve the timeframe list.
    if args.all_timeframes:
        timeframes = ["1d"] + [tf for tf in discover_intraday_timeframes() if tf.lower() not in _DAILY_TIMEFRAMES]
    else:
        timeframes = [tf.strip() for tf in args.timeframe.split(",") if tf.strip()]
    if not timeframes:
        print("[Backtest_Seeder] No timeframes resolved.")
        raise SystemExit(1)

    # ── Single-symbol file mode (kept simple: one symbol, one timeframe) ─────
    if args.candles_file:
        if not args.symbol:
            print("[Backtest_Seeder] --candles-file requires --symbol.")
            raise SystemExit(1)
        candles = _load_candles_file(args.candles_file)
        summary = seed(args.symbol, timeframes[0], limit=args.limit, candles=candles,
                       cfg=cfg, purge_first=not args.no_purge, dry_run=args.dry_run)
        print("\n[Backtest_Seeder] Summary:")
        print(json.dumps(summary, indent=2))
        return

    # ── Resolve the symbol list ──────────────────────────────────────────────
    if args.all_symbols:
        symbols = discover_symbols(args.source)
        if not symbols:
            print("[Backtest_Seeder] No symbols discovered in QuestDB.")
            raise SystemExit(1)
        print(f"[Backtest_Seeder] Discovered {len(symbols)} symbol(s): {', '.join(symbols)}")
    elif args.symbol:
        symbols = [args.symbol]
    else:
        print("[Backtest_Seeder] Provide --symbol or --all-symbols.")
        raise SystemExit(1)

    # ── Single symbol + single timeframe → detailed per-setup summary ────────
    if len(symbols) == 1 and len(timeframes) == 1:
        try:
            summary = seed(symbols[0], timeframes[0], limit=args.limit, cfg=cfg,
                           purge_first=not args.no_purge, dry_run=args.dry_run, source=args.source)
        except Exception as e:
            print(f"[Backtest_Seeder] FAILED: {e}")
            raise SystemExit(1)
        print("\n[Backtest_Seeder] Summary:")
        print(json.dumps(summary, indent=2))
        return

    # ── Batch mode (multi-symbol and/or multi-timeframe) ─────────────────────
    summary = seed_batch(symbols, timeframes, limit=args.limit, cfg=cfg,
                         purge_first=not args.no_purge, dry_run=args.dry_run, source=args.source)
    print("\n[Backtest_Seeder] Batch Summary:")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
