"""Backtest_Seeder — give the Deep Quant agent a track record on day one.

Phase 2.5 of the trading-edge roadmap. The live Trade_Journal (journal.py) only
learns as real trades accumulate and resolve, which means the agent's
`get_trade_performance` is empty until then. This seeder replays HISTORICAL
candles through a set of deterministic, rule-based setups and scores them with
the SAME conservative outcome logic the live journal uses, then writes the
resolved trades into the journal tagged ``source='backtest'``.

Why this is honest and useful:
  * The seeded trades are tagged with the SAME setup fingerprint
    (direction / macro alignment / predictive agreement / value-area location)
    as live LLM decisions, so per-setup statistics are directly comparable and
    give the agent a meaningful PRIOR on which setup *types* historically work.
  * Scoring uses the same worst-case fill assumption (a candle that straddles
    both stop and target counts as a loss), so the prior never flatters itself.
  * Seeded rows carry ``source='backtest'`` so they are always distinguishable
    from — and purgeable independently of — live trades.

IMPORTANT CAVEAT (surfaced to the user): the seeder's setups are generated by
simple deterministic RULES, not by the LLM agent. So the prior reflects how a
*setup type* behaves historically, not how this specific model would trade. It
is a starting calibration, not ground truth for the agent's own edge — live
trades gradually dominate the statistics.

Usage:
    python backtest.py --symbol RELIANCE --timeframe 15m --limit 3000
    python backtest.py --symbol RELIANCE --timeframe 1d --candles-file hist.json
    python backtest.py --symbol RELIANCE --timeframe 15m --dry-run   # no DB writes
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass, field, replace
from typing import List, Optional

import httpx

import forecaster
import journal
import regime
import rs
import session
import trade_manager
# Reuse the AUTHORITATIVE volume-profile math and EMA helper so seeded levels
# match what the live agent and the UI compute.
from tools import _compute_volume_profile, calculate_ema

RUST_SERVER_URL = "http://localhost:8084"
# QuestDB HTTP query endpoint — the historical archive. Reading candles here lets
# the seeder pull real history WITHOUT the Tauri desktop app / Rust tool server
# running; only QuestDB (docker-compose) needs to be up.
QUESTDB_HTTP_URL = os.getenv("QUESTDB_HTTP_URL", "http://127.0.0.1:9000")

# Timeframes stored in the daily `historical_candles` table; everything else is
# read from `historical_intraday` filtered by its `timeframe` column.
_DAILY_TIMEFRAMES = {"1d", "d", "day", "1day", "1w", "1week", "week", "daily"}


# ── Configuration ─────────────────────────────────────────────────────────────

@dataclass
class BacktestConfig:
    lookback: int = 120           # bars of context the rules "see" per decision
    ema_fast: int = 9
    ema_slow: int = 21
    atr_period: int = 14
    ols_window: int = 20          # bars used for the predictive-slope proxy
    atr_stop_mult: float = 1.5    # stop distance = 1.5 x ATR (matches validator)
    risk_reward: float = 2.0      # target distance = RR x stop (matches validator)
    cooldown_bars: int = 5        # min bars between successive signals
    max_horizon_bars: int = 200   # give a trade this many bars to resolve
    profile_rows: int = 24
    value_area_percent: float = 70.0
    record_unresolved: bool = False  # skip trades that never hit stop/target
    regime_gate_enabled: bool = False  # with-gate run drops unfavorable signals (gate logic: task 13.2)
    rs_filter_enabled: bool = False  # with-filter run drops misaligned signals (filter logic: task 13.2)
    forecast_filter_enabled: bool = False  # with-forecast run drops forecast-misaligned signals (filter logic: task 14.2)
    session_filter_enabled: bool = False  # with-filter run drops session-unfavorable signals (filter logic: task 9.1)
    manage_trades: bool = False  # managed run: seed trades carry the default Management_Plan, scored via the Trade_Manager (R7.1)


def _is_num(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)


# ── Indicator helpers (deterministic, pure) ──────────────────────────────────

def _atr(candles: List[dict], period: int) -> float:
    """Average True Range over the last ``period`` bars of ``candles``."""
    trs = []
    for i in range(1, len(candles)):
        h, l = candles[i].get("high"), candles[i].get("low")
        pc = candles[i - 1].get("close")
        if not (_is_num(h) and _is_num(l) and _is_num(pc)):
            continue
        trs.append(max(h - l, abs(h - pc), abs(l - pc)))
    if not trs:
        return 0.0
    window = trs[-period:] if len(trs) >= period else trs
    return sum(window) / len(window)


def _ols_slope(values: List[float]) -> float:
    """Least-squares slope of ``values`` against their index (predictive proxy)."""
    n = len(values)
    if n < 2:
        return 0.0
    xs = list(range(n))
    mx = sum(xs) / n
    my = sum(values) / n
    num = sum((xs[i] - mx) * (values[i] - my) for i in range(n))
    den = sum((xs[i] - mx) ** 2 for i in range(n))
    return num / den if den else 0.0


# ── Signal construction ───────────────────────────────────────────────────────

def _macro_conflict_str(action: str, bias: str) -> str:
    """Mirror graph.py's macro-trend-conflict phrasing so tagging matches."""
    opposes = (action == "BUY" and bias == "Bearish") or (action == "SELL" and bias == "Bullish")
    if opposes:
        return f"MACRO CONFLICT: {action} opposes the 1D trend bias ({bias})."
    return f"Aligned with the 1D trend bias ({bias})."


def _predictive_conflict_str(action: str, slope: float) -> str:
    """Mirror graph.py's predictive-conflict phrasing so tagging matches."""
    if slope > 0:
        proj = "Up"
    elif slope < 0:
        proj = "Down"
    else:
        proj = "Flat"
    agent = "Up" if action == "BUY" else "Down"
    if proj == "Flat":
        return f"Predictive projection is {proj} (source: ols_slope); no directional conflict."
    if {proj, agent} == {"Up", "Down"}:
        return f"CONFLICT: predictive projection is {proj} (source: ols_slope) but the trade bias is {agent}."
    return f"No predictive conflict: projection {proj} aligns with trade bias {agent} (source: ols_slope)."


def _build_decision(action: str, entry: float, atr: float, bias: str, slope: float,
                    vp: dict, created_at: float, cfg: BacktestConfig) -> Optional[dict]:
    """Construct a journal-shaped decision with validator-passing levels.

    Levels are set so stop distance == ``atr_stop_mult x ATR`` and reward ==
    ``risk_reward x`` risk, i.e. they always satisfy the live Trade_Validator
    (stop >= 1.5x ATR, RR >= 1:2) — the same bar the live agent must clear.
    """
    if not (_is_num(entry) and _is_num(atr)) or atr <= 0:
        return None
    risk = cfg.atr_stop_mult * atr
    reward = cfg.risk_reward * risk
    if action == "BUY":
        stop_loss = entry - risk
        take_profit = entry + reward
    else:  # SELL
        stop_loss = entry + risk
        take_profit = entry - reward

    return {
        "action": action,
        "conviction_score": 60,
        "entry": round(entry, 4),
        "stop_loss": round(stop_loss, 4),
        "take_profit": round(take_profit, 4),
        "atr_14": round(atr, 4),
        "created_at": created_at,
        "source": "backtest",
        "defensibility": {
            "risk_reward": round(reward / risk, 4) if risk > 0 else None,
            "macro_trend_conflict": _macro_conflict_str(action, bias),
            "predictive_conflict": _predictive_conflict_str(action, slope),
            "volume_profile": {
                "poc": vp.get("poc"),
                "vah": vp.get("vah"),
                "val": vp.get("val"),
                "price_vs_value_area": vp.get("price_vs_value_area"),
            },
        },
    }


def _signal_for_bar(window: List[dict], created_at: float, cfg: BacktestConfig) -> Optional[dict]:
    """Apply the deterministic rule set to a window and return a decision or None.

    Rules (priority order):
      A) Trend pullback (aligned): macro bullish + price at/below Value-Area Low
         → BUY; macro bearish + price at/above Value-Area High → SELL.
      B) Over-extension fade (counter-trend): price stretched well beyond the
         value area against an opposing macro → fade it (produces macro:against
         samples so the prior learns counter-trend setups are riskier).
    """
    closes = [c.get("close") for c in window if _is_num(c.get("close"))]
    if len(closes) < max(cfg.ema_slow, cfg.ols_window) + 1:
        return None

    ema_fast = calculate_ema(closes, cfg.ema_fast)
    ema_slow = calculate_ema(closes, cfg.ema_slow)
    if not (_is_num(ema_fast) and _is_num(ema_slow)) or ema_fast == ema_slow:
        return None
    bias = "Bullish" if ema_fast > ema_slow else "Bearish"

    atr = _atr(window, cfg.atr_period)
    if atr <= 0:
        return None
    slope = _ols_slope(closes[-cfg.ols_window:])

    vp = _compute_volume_profile(window, rows=cfg.profile_rows, value_area_percent=cfg.value_area_percent)
    vah, val = vp.get("vah"), vp.get("val")
    if not (_is_num(vah) and _is_num(val)):
        return None

    entry = closes[-1]

    # ── Rule A: trend-aligned pullback to the value-area edge ────────────────
    if bias == "Bullish" and entry <= val + 0.25 * atr:
        return _build_decision("BUY", entry, atr, bias, slope, vp, created_at, cfg)
    if bias == "Bearish" and entry >= vah - 0.25 * atr:
        return _build_decision("SELL", entry, atr, bias, slope, vp, created_at, cfg)

    # ── Rule B: counter-trend fade of an over-extension beyond value ─────────
    if bias == "Bullish" and entry > vah + 1.0 * atr:
        return _build_decision("SELL", entry, atr, bias, slope, vp, created_at, cfg)
    if bias == "Bearish" and entry < val - 1.0 * atr:
        return _build_decision("BUY", entry, atr, bias, slope, vp, created_at, cfg)

    return None


# ── Regime labeling (point-in-time, look-ahead-free) ─────────────────────────

def _regime_defensibility_entry(regime_result: Optional[dict]) -> dict:
    """Map a ``regime.classify_regime`` result to the defensibility regime entry.

    Mirrors the shape ``graph._regime_entry`` writes and ``journal._regime_tag``
    reads, so seeded trades are tagged identically to live LLM decisions:

      * a usable Regime_Label  -> ``{"available": True, trend_state,
        volatility_state, favorability, measures, [symbol/timeframe/candles_used]}``
        — copied VERBATIM from the classifier output (no inference, R10.3).
      * an Unavailable_Marker / non-dict / label missing any categorical state
        -> ``{"available": False, "reason": ...}`` with NO fabricated states (R7.3/AD-4).
    """
    if not isinstance(regime_result, dict):
        return {"available": False, "reason": "no regime result"}
    # Honest Unavailable_Marker from the classifier — never fabricate states.
    if regime_result.get("unavailable") is True:
        return {"available": False, "reason": regime_result.get("reason") or "regime unavailable"}

    trend_state = regime_result.get("trend_state")
    volatility_state = regime_result.get("volatility_state")
    favorability = regime_result.get("favorability")
    if trend_state is None or volatility_state is None or favorability is None:
        return {"available": False, "reason": "no usable regime label"}

    src_measures = regime_result.get("measures")
    measures = dict(src_measures) if isinstance(src_measures, dict) else {}
    entry = {
        "available": True,
        "trend_state": trend_state,
        "volatility_state": volatility_state,
        "favorability": favorability,
        "measures": measures,
    }
    for k in ("symbol", "timeframe", "candles_used"):
        if k in regime_result:
            entry[k] = regime_result[k]
    return entry


def _relative_strength_defensibility_entry(rs_result: Optional[dict]) -> dict:
    """Map a ``rs.classify_relative_strength`` result to the defensibility entry.

    Mirrors the shape ``graph._relative_strength_entry`` writes and
    ``journal._relative_strength_tag`` reads, so seeded trades are tagged
    identically to live LLM decisions:

      * a usable Relative_Strength_Label -> ``{"available": True, index_direction,
        relative_strength_state, alignment, measures, benchmark,
        [symbol/timeframe/aligned_candles]}`` — copied VERBATIM from the
        classifier output (no inference, R8.2/R11.3).
      * an Unavailable_Marker / non-dict / label missing any categorical state ->
        ``{"available": False, "reason": ...}`` with NO fabricated states
        (R5.3/AD-4); a signal so labelled is RETAINED by the with-filter run and
        tagged ``rs:unknown`` by the journal (R11.6).
    """
    if not isinstance(rs_result, dict):
        return {"available": False, "reason": "no relative-strength result"}
    # Honest Unavailable_Marker from the calculator — never fabricate states.
    if rs_result.get("unavailable") is True:
        return {"available": False, "reason": rs_result.get("reason") or "relative strength unavailable"}

    index_direction = rs_result.get("index_direction")
    relative_strength_state = rs_result.get("relative_strength_state")
    alignment = rs_result.get("alignment")
    if index_direction is None or relative_strength_state is None or alignment is None:
        return {"available": False, "reason": "no usable relative-strength label"}

    src_measures = rs_result.get("measures")
    measures = dict(src_measures) if isinstance(src_measures, dict) else {}
    entry = {
        "available": True,
        "index_direction": index_direction,
        "relative_strength_state": relative_strength_state,
        "alignment": alignment,
        "measures": measures,
    }
    for k in ("benchmark", "symbol", "timeframe", "aligned_candles"):
        if k in rs_result:
            entry[k] = rs_result[k]
    return entry


def _forecast_defensibility_entry(fc_result: Optional[dict]) -> dict:
    """Map a ``forecaster.forecast`` result to the defensibility forecast entry.

    Mirrors the shape ``graph._forecast_entry`` writes and ``journal._forecast_tag``
    / ``journal._forecast_up_probability`` read, so seeded trades are labelled
    identically to live LLM decisions:

      * a usable Forecast_Label -> ``{"available": True, projected_direction,
        up_probability, expected_move_atr, forecast_confidence, forecast_alignment,
        measures, [symbol/timeframe/candles_used]}`` — copied VERBATIM from the
        forecaster output (no inference, R9.2).
      * an Unavailable_Marker / non-dict / label missing a categorical field or a
        finite probability/confidence -> ``{"available": False, "reason": ...}``
        with NO fabricated fields (AD-5/R6.3); a signal so labelled is RETAINED by
        the with-forecast run (R13.4) and tagged ``fc:unknown`` by the journal
        (R11.2). ``journal._forecast_up_probability`` then persists ``NULL``.
    """
    if not isinstance(fc_result, dict):
        return {"available": False, "reason": "no forecast result"}
    # Honest Unavailable_Marker from the forecaster — never fabricate fields.
    if fc_result.get("unavailable") is True:
        return {"available": False, "reason": fc_result.get("reason") or "forecast unavailable"}

    projected_direction = fc_result.get("projected_direction")
    up_probability = fc_result.get("up_probability")
    expected_move_atr = fc_result.get("expected_move_atr")
    forecast_confidence = fc_result.get("forecast_confidence")
    forecast_alignment = fc_result.get("forecast_alignment")

    # A usable Forecast_Label must carry a projected_direction and a
    # forecast_alignment from their fixed enums, plus finite numeric
    # up_probability and forecast_confidence; anything missing means no usable
    # label, and we must not fabricate one (R9.3).
    if (
        projected_direction not in ("up", "down", "flat")
        or forecast_alignment not in ("aligned", "misaligned", "neutral")
        or not _is_num(up_probability)
        or not _is_num(forecast_confidence)
    ):
        return {"available": False, "reason": "no usable forecast label"}

    # Copy the named measures verbatim (each is a finite number or null per the
    # forecaster contract); never infer a measure not reported.
    src_measures = fc_result.get("measures")
    measures = {}
    if isinstance(src_measures, dict):
        for k in forecaster._FORECAST_MEASURE_FIELDS:
            measures[k] = src_measures.get(k)

    entry = {
        "available": True,
        "projected_direction": projected_direction,
        "up_probability": up_probability,
        # expected_move_atr is finite-number-or-null per the contract; copy it
        # verbatim (including null) without substituting a value.
        "expected_move_atr": expected_move_atr,
        "forecast_confidence": forecast_confidence,
        "forecast_alignment": forecast_alignment,
        "measures": measures,
    }
    for k in ("symbol", "timeframe", "candles_used"):
        if k in fc_result:
            entry[k] = fc_result[k]
    return entry


def _session_defensibility_entry(session_result: Optional[dict]) -> dict:
    """Map a ``session.classify_session`` result to the defensibility session entry.

    Mirrors the shape ``graph._session_entry`` writes and ``journal._session_tag``
    reads, so seeded trades are labelled identically to live LLM decisions:

      * a usable Session_Label -> ``{"available": True, session_phase,
        minutes_since_open, minutes_until_close, expiry_context, time_favorability,
        [symbol/timeframe]}`` — copied VERBATIM from the classifier output (no
        inference, R8.2/R11.3).
      * an Unavailable_Marker / non-dict / label missing a categorical field ->
        ``{"available": False, "reason": ...}`` with NO fabricated fields
        (AD-5/R5.2); a signal so labelled is RETAINED by the with-filter run and
        tagged ``sess:unknown`` by the journal (R11.5).
    """
    if not isinstance(session_result, dict):
        return {"available": False, "reason": "no session result"}
    # Honest Unavailable_Marker from the classifier — never fabricate fields.
    if session_result.get("unavailable") is True:
        return {"available": False, "reason": session_result.get("reason") or "session unavailable"}

    session_phase = session_result.get("session_phase")
    time_favorability = session_result.get("time_favorability")
    # A usable Session_Label must carry a session_phase and a time_favorability;
    # anything missing means no usable label, and we must not fabricate one.
    if session_phase is None or time_favorability is None:
        return {"available": False, "reason": "no usable session label"}

    src_expiry = session_result.get("expiry_context")
    expiry_context = dict(src_expiry) if isinstance(src_expiry, dict) else {}
    entry = {
        "available": True,
        "session_phase": session_phase,
        # minutes_since_open / minutes_until_close are finite-number-or-null per
        # the classifier contract; copy them verbatim (including null) without
        # substituting a value.
        "minutes_since_open": session_result.get("minutes_since_open"),
        "minutes_until_close": session_result.get("minutes_until_close"),
        "expiry_context": expiry_context,
        "time_favorability": time_favorability,
    }
    for k in ("symbol", "timeframe"):
        if k in session_result:
            entry[k] = session_result[k]
    return entry


def _candles_at_or_before(candle_series: Optional[List[dict]], cutoff_ts) -> List[dict]:
    """Point-in-time slice: rows whose ``timestamp_ms`` is at or before ``cutoff_ts``.

    Used to slice the BENCHMARK series look-ahead-free against a signal candle's
    timestamp (R11.1): the benchmark is a SEPARATE series from the symbol, so it
    cannot be index-sliced like ``candles[:i+1]`` and must be filtered by
    timestamp instead. Returns an empty list for a missing series or a
    non-numeric cutoff; never raises.
    """
    if not isinstance(candle_series, list) or not _is_num(cutoff_ts):
        return []
    return [
        c for c in candle_series
        if isinstance(c, dict) and _is_num(c.get("timestamp_ms")) and c["timestamp_ms"] <= cutoff_ts
    ]


def _signal_is_unfavorable(decision: dict) -> bool:
    """Return True only when the signal carries an AVAILABLE ``unfavorable`` label.

    This is the with-gate drop predicate (R10.2): a directional signal whose
    regime favorability is the available label ``unfavorable`` for its setup type
    is dropped. A signal whose regime is an Unavailable_Marker is reported as
    ``{"available": False, ...}`` by ``_regime_defensibility_entry`` and is
    RETAINED — never excluded on the basis of regime (R10.6). ``favorable`` and
    ``neutral`` signals are likewise retained.
    """
    regime_entry = decision.get("defensibility", {}).get("regime") or {}
    return regime_entry.get("available") is True and regime_entry.get("favorability") == "unfavorable"


def _signal_is_misaligned(decision: dict) -> bool:
    """Return True only when the signal carries an AVAILABLE ``misaligned`` label.

    This is the with-filter drop predicate (R11.2): a directional signal whose
    relative-strength Alignment is the available label ``misaligned`` for its
    direction is dropped. A signal whose relative strength is an
    Unavailable_Marker is reported as ``{"available": False, ...}`` by
    ``_relative_strength_defensibility_entry`` and is RETAINED — never excluded on
    the basis of relative strength being unavailable (R11.6). ``aligned`` and
    ``neutral`` signals are likewise retained.
    """
    rs_entry = decision.get("defensibility", {}).get("relative_strength") or {}
    return rs_entry.get("available") is True and rs_entry.get("alignment") == "misaligned"


def _signal_is_forecast_misaligned(decision: dict) -> bool:
    """Return True only when the signal carries an AVAILABLE ``misaligned`` forecast.

    This is the with-forecast drop predicate (R13.2): a directional signal whose
    Forecast_Alignment is the available label ``misaligned`` for its direction is
    dropped. A signal whose forecast is an Unavailable_Marker is reported as
    ``{"available": False, ...}`` by ``_forecast_defensibility_entry`` and is
    RETAINED — never excluded on the basis of the forecast being unavailable
    (R13.4) — as are ``aligned`` and ``neutral`` signals. Mirrors
    ``_signal_is_misaligned`` (the relative-strength predicate).
    """
    fc_entry = decision.get("defensibility", {}).get("forecast") or {}
    return fc_entry.get("available") is True and fc_entry.get("forecast_alignment") == "misaligned"


def _signal_is_session_unfavorable(decision: dict) -> bool:
    """Return True only when the signal carries an AVAILABLE ``unfavorable`` session.

    This is the with-filter drop predicate (R11.2): a directional signal whose
    Time_Favorability is the available label ``unfavorable`` for its time window
    is dropped. A signal whose session result is an Unavailable_Marker is reported
    as ``{"available": False, ...}`` by ``_session_defensibility_entry`` and is
    RETAINED — never excluded on the basis of the session being unavailable
    (R11.5) — as are ``favorable`` and ``neutral`` signals. Mirrors
    ``_signal_is_unfavorable`` (the regime gate predicate).
    """
    sess_entry = decision.get("defensibility", {}).get("session") or {}
    return sess_entry.get("available") is True and sess_entry.get("time_favorability") == "unfavorable"


# ── Scoring against future candles (mirrors journal._score_one) ───────────────

def _score_signal(decision: dict, future: List[dict], cfg: BacktestConfig):
    """Score a decision against the bars that follow it.

    Returns (status, outcome_price, outcome_at_seconds, r_multiple) or None when
    there are no future bars at all. Worst-case: a bar touching both levels is a
    loss. A trade that resolves neither within ``max_horizon_bars`` is expired.
    """
    action = decision["action"]
    entry = decision["entry"]
    sl = decision["stop_loss"]
    tp = decision["take_profit"]
    risk = abs(entry - sl)
    if risk <= 0:
        return None
    rr = abs(tp - entry) / risk

    horizon = future[: cfg.max_horizon_bars]
    if not horizon:
        return None

    last_ts = None
    for c in horizon:
        hi, lo, ts = c.get("high"), c.get("low"), c.get("timestamp_ms")
        if not (_is_num(hi) and _is_num(lo)):
            continue
        last_ts = ts if _is_num(ts) else last_ts
        out_at = (ts / 1000.0) if _is_num(ts) else None
        hit_tp = hi >= tp if action == "BUY" else lo <= tp
        hit_sl = lo <= sl if action == "BUY" else hi >= sl
        if hit_sl and hit_tp:
            return "loss", sl, out_at, -1.0
        if hit_tp:
            return "win", tp, out_at, round(rr, 4)
        if hit_sl:
            return "loss", sl, out_at, -1.0

    return "expired", None, (last_ts / 1000.0 if _is_num(last_ts) else None), None


# ── Managed scoring via the Trade_Manager (R7.1, R7.2) ───────────────────────
# A managed seeded trade is scored by the SINGLE source of truth for the
# exit-simulation math — ``trade_manager.simulate_plan`` — never by reimplementing
# the multi-leg fill / breakeven / trail logic here (R7.2, AD-2). The backtest
# path and the live journal-scoring path both call back into the same simulator,
# feeding only different candle windows. A single-target seeded trade keeps using
# the legacy ``_score_signal`` path above so its outcome is byte-for-byte today's.

def _managed_outcome(result, horizon: List[dict]):
    """Map a ``SimulationResult`` onto ``_score_signal``'s outcome tuple.

    Returns (status, outcome_price, outcome_at_seconds, r_multiple) or None,
    matching the shape ``_score_signal`` returns so the seeding path stays
    uniform across managed and single-target trades:

      * ``invalid`` (zero initial-stop distance) -> None (skip, as ``_score_signal``
        skips a zero-risk bracket).
      * ``open``    (no candle reached the stop and never fully scaled out within
        the horizon) -> ("expired", None, last-bar-ts, None).
      * ``resolved`` with a positive fraction-weighted ``Realized_R`` -> a "win"
        at the final fill price / time and that R; a non-positive ``Realized_R``
        -> a "loss" (R6.4 win/loss convention: positive R is a win).
    """
    if result.status == "invalid":
        return None
    if result.status == "open":
        last_ts = None
        for c in horizon:
            ts = c.get("timestamp_ms") if isinstance(c, dict) else None
            if _is_num(ts):
                last_ts = ts
        return "expired", None, (last_ts / 1000.0 if _is_num(last_ts) else None), None

    # resolved — derive the binary status from the multi-leg Realized_R and report
    # the final fill (the last recorded exit in the Exit_Breakdown) as the outcome.
    realized_r = result.realized_r
    status = "win" if (_is_num(realized_r) and realized_r > 0) else "loss"
    last_fill = result.fills[-1] if result.fills else None
    out_price = last_fill.price if last_fill is not None else None
    out_at = (last_fill.timestamp_ms / 1000.0) if (last_fill is not None and _is_num(last_fill.timestamp_ms)) else None
    r_mult = round(realized_r, 4) if _is_num(realized_r) else None
    return status, out_price, out_at, r_mult


def _score_signal_managed(plan, future: List[dict], cfg: BacktestConfig, tm_config):
    """Score a managed ``ManagementPlan`` against the bars that follow the signal.

    Invokes ``trade_manager.simulate_plan`` against the candles at or after the
    signal's entry candle (the caller passes ``candles[i + 1:]`` — the bars after
    the entry bar's close, the same window the single-target ``_score_signal``
    uses, capped to ``max_horizon_bars``), reusing the Trade_Manager functions
    rather than reimplementing the exit logic (R7.1, R7.2). Returns
    ``(outcome_tuple_or_None, simulation_result_or_None)`` so the caller can both
    record the outcome and cite the simulated ``Exit_Breakdown`` in the
    defensibility record. Never raises — ``simulate_plan`` reports degeneracy as
    data (open / invalid), not exceptions.
    """
    horizon = future[: cfg.max_horizon_bars]
    if not horizon:
        return None, None
    result = trade_manager.simulate_plan(plan, horizon, tm_config)
    return _managed_outcome(result, horizon), result


def _management_defensibility_entry(plan, sim_result) -> dict:
    """Map a Management_Plan (+ optional simulation) to the defensibility entry.

    Labels a seeded trade with its management style so the journal's
    management-style fingerprint can tag it (``tm:<value>``) and per-management-
    style win-rate / expectancy become measurable (R7.3). Mirrors the shape
    ``graph._management_entry`` (task 12) writes and the journal management-style
    derivation (task 9.2) reads, so seeded trades are labelled identically to live
    LLM decisions — exactly as ``_regime_defensibility_entry`` /
    ``_relative_strength_defensibility_entry`` / ``_forecast_defensibility_entry``
    mirror their live counterparts.

    Cites ONLY the declared plan and the Trade_Manager output — never fabricates
    an exit: the simulated ``Exit_Breakdown`` + ``Realized_R`` are included only
    when a ``sim_result`` is supplied (managed trades); a single-target trade
    records the plan as single-target with no fabricated scale-out legs.
    """
    legs = [{"target": leg.target, "fraction": leg.fraction} for leg in (plan.legs or ())]
    breakeven = None
    if plan.breakeven is not None:
        breakeven = {"price": plan.breakeven.price, "r_multiple": plan.breakeven.r_multiple}
    trailing = None
    if plan.trailing is not None:
        trailing = {"atr_multiple": plan.trailing.atr_multiple, "r_increment": plan.trailing.r_increment}

    entry = {
        "available": True,
        # The single fixed-enumeration management-style value (R7.3, R11.2); the
        # journal namespaces it as ``tm:<style>`` at its fixed tag position.
        "style": trade_manager.management_style_tag(plan),
        "action": plan.action,
        "entry": plan.entry,
        "initial_stop": plan.initial_stop,
        "legs": legs,
        "breakeven": breakeven,
        "trailing": trailing,
        "atr_14": plan.atr_14,
    }
    # Where the plan was simulated (managed trades), cite the real Exit_Breakdown
    # + Realized_R verbatim from the Trade_Manager output (no fabrication).
    if sim_result is not None:
        entry["status"] = sim_result.status
        entry["realized_r"] = sim_result.realized_r
        entry["residual_fraction"] = sim_result.residual_fraction
        entry["exit_breakdown"] = [
            {
                "index": f.index,
                "price": f.price,
                "fraction": f.fraction,
                "leg_r": f.leg_r,
                "timestamp_ms": f.timestamp_ms,
                "kind": f.kind,
            }
            for f in sim_result.fills
        ]
    return entry


# ── Orchestration ─────────────────────────────────────────────────────────────

def generate_and_score(candles: List[dict], symbol: str, timeframe: str,
                       cfg: BacktestConfig,
                       benchmark_candles: Optional[List[dict]] = None,
                       benchmark: Optional[str] = None) -> List[dict]:
    """Walk the candle history, emit rule-based signals, and score each one.

    Returns a list of result records: {decision, status, outcome_price,
    outcome_at, r_multiple}. Pure given the candle data (no DB / network).

    ``benchmark_candles`` is the Benchmark_Index series for the run (resolved once
    by the caller, e.g. ``seed``, via ``_resolve_candles`` for the benchmark
    symbol/timeframe). When omitted, relative strength degrades to an honest
    Unavailable_Marker for every signal (no benchmark to compare against) and the
    seeded trades are tagged ``rs:unknown`` — the without-data behaviour stays
    unchanged.
    """
    results: List[dict] = []
    n = len(candles)
    if n < cfg.lookback + 2:
        return results

    # Resolve the regime thresholds ONCE, reusing the SAME resolver the live
    # get_market_regime tool uses (R10.5, R11.6) — the seeder never reimplements
    # the regime math.
    regime_config = regime.resolve_regime_config()

    # Resolve the relative-strength parameters ONCE, reusing the SAME resolver the
    # live get_relative_strength tool uses (R11.5, R12.6) — the seeder never
    # reimplements the relative-strength math. The Benchmark_Index is likewise
    # resolved once per run (R11.1).
    rs_config = rs.resolve_rs_config()
    if benchmark is None:
        benchmark = rs.resolve_benchmark(symbol)

    # Resolve the forecaster parameters ONCE, reusing the SAME resolver the live
    # get_forecast tool uses (R13.5, R14.5) — the seeder never reimplements the
    # forecast math. Each signal's forecast is computed point-in-time from this
    # single resolved config.
    forecaster_config = forecaster.resolve_forecaster_config()

    # Resolve the Trade_Manager parameters ONCE, reusing the SAME resolver the
    # live journal-scoring path uses (R13.5) — the seeder never reimplements the
    # exit-simulation math nor its parameter resolution. Managed seeded trades are
    # scored by feeding this single resolved config (and the default plan built
    # from it) to ``trade_manager.simulate_plan`` (R7.1, R7.2, AD-2).
    trade_manager_config = trade_manager.resolve_trade_manager_config()

    # Resolve the session parameters ONCE, reusing the SAME resolver the live
    # get_session_context tool uses (R11.6, R12.6) — the seeder never reimplements
    # the session date math. Each signal's session is classified point-in-time
    # from the timestamp of its OWN candle using this single resolved config.
    session_config = session.resolve_session_config()

    cooldown_until = -1
    for i in range(cfg.lookback - 1, n - 1):
        if i < cooldown_until:
            continue
        window = candles[i - cfg.lookback + 1: i + 1]
        ts = candles[i].get("timestamp_ms")
        created_at = (ts / 1000.0) if _is_num(ts) else 0.0
        decision = _signal_for_bar(window, created_at, cfg)
        if decision is None:
            continue

        # Classify the signal's regime using ONLY candles at or before the
        # signal's candle (index ``i``) — the point-in-time slice ``candles[:i+1]``
        # carries no later candles, so there is no look-ahead (R10.1). The same
        # classifier as the live tool path produces the label (R10.5).
        regime_result = regime.classify_regime(
            candles[: i + 1], regime_config, symbol=symbol, timeframe=timeframe
        )
        # Label the seeded trade with its Regime_Label so journal._regime_tag can
        # tag it (R10.3); shape mirrors graph._regime_entry.
        decision.setdefault("defensibility", {})["regime"] = _regime_defensibility_entry(regime_result)

        # Classify the signal's relative strength look-ahead-free (R11.1). Both
        # series are sliced to timestamps AT OR BEFORE the signal candle's
        # timestamp: the symbol series is index-sliced ``candles[:i+1]`` (already
        # point-in-time, ascending), and the SEPARATE benchmark series is filtered
        # by ``timestamp_ms <= signal ts`` since it cannot be index-aligned. The
        # signal's direction (BUY/SELL) is passed as ``proposed_direction``. The
        # SAME calculator as the live tool path produces the label (R11.5);
        # ``classify_relative_strength`` time-aligns the two windows internally.
        symbol_window = candles[: i + 1]
        benchmark_window = _candles_at_or_before(benchmark_candles, ts)
        rs_result = rs.classify_relative_strength(
            symbol_window, benchmark_window, rs_config,
            proposed_direction=decision.get("action"),
            symbol=symbol, benchmark=benchmark, timeframe=timeframe,
        )
        # Label the seeded trade with its Relative_Strength_Label so
        # journal._relative_strength_tag can tag it (R11.3); shape mirrors
        # graph._relative_strength_entry.
        decision["defensibility"]["relative_strength"] = _relative_strength_defensibility_entry(rs_result)

        # Classify the signal's forecast look-ahead-free (R13.1): the
        # Volatility_Aware_Forecaster sees ONLY candles AT OR BEFORE the signal
        # candle (the point-in-time slice ``candles[:i+1]`` carries no later
        # candles), and the signal's direction (BUY/SELL) is passed as
        # ``proposed_direction`` so the Forecast_Alignment is computed against the
        # trade. The SAME forecaster as the live tool path produces the label
        # (R13.5); the seeder never reimplements the forecast math.
        fc_result = forecaster.forecast(
            candles[: i + 1], forecaster_config,
            proposed_direction=decision.get("action"),
            symbol=symbol, timeframe=timeframe,
        )
        # Label the seeded trade with its Forecast_Label so journal._forecast_tag
        # can tag it and journal.record_backtest_trade persists its Up_Probability
        # (R11.4); shape mirrors graph._forecast_entry.
        decision["defensibility"]["forecast"] = _forecast_defensibility_entry(fc_result)

        # Classify the signal's session using the timestamp of the signal's OWN
        # candle (index ``i``) via the SAME classifier as the live tool path
        # (R11.1, R11.6). A candle's timestamp is intrinsic to that candle, so
        # this is inherently look-ahead-free — no later candle informs the label.
        session_result = session.classify_session(
            ts, session_config, symbol=symbol, timeframe=timeframe,
        )
        # Label the seeded trade with its Session_Phase and expiry flag so
        # journal._session_tag can tag it (R11.3); shape mirrors graph._session_entry.
        decision["defensibility"]["session"] = _session_defensibility_entry(session_result)

        # ── Score the signal (managed via the Trade_Manager, else single-target) ─
        # A managed run (``cfg.manage_trades``) attaches the uniform default
        # Management_Plan built from the resolved Trade_Manager config and scores
        # it with ``trade_manager.simulate_plan`` against the candles after the
        # entry bar (R7.1) — reusing the SINGLE source of truth for the exit math
        # rather than reimplementing it (R7.2). A single-target run keeps the
        # legacy ``_score_signal`` path so its outcome is byte-for-byte today's.
        future = candles[i + 1:]
        if cfg.manage_trades:
            plan = trade_manager.default_management_plan(
                decision["action"], decision["entry"], decision["stop_loss"],
                decision.get("atr_14"), trade_manager_config,
            )
            scored, sim_result = _score_signal_managed(plan, future, cfg, trade_manager_config)
        else:
            # Single_Target_Trade: the degenerate one-leg plan models today's
            # bracket purely for the management-style label; scoring stays on the
            # existing conservative ``_score_signal`` path (R3.6 / R14.5).
            plan = trade_manager.single_target_plan(
                decision["entry"], decision["stop_loss"], decision["take_profit"],
            )
            sim_result = None
            scored = _score_signal(decision, future, cfg)
        if scored is None:
            continue
        status, out_price, out_at, r_mult = scored

        # Label the seeded trade with its management style (R7.3) and cite the
        # plan (and, for a managed trade, the simulated Exit_Breakdown + Realized_R)
        # in the defensibility record. The journal's public seeding API
        # (``record_backtest_trade``) receives this whole ``decision`` dict, so the
        # management style/tag is threaded into the journal's management-style
        # fingerprint without editing journal.py.
        decision["defensibility"]["management"] = _management_defensibility_entry(plan, sim_result)
        decision["management_plan"] = trade_manager.plan_to_json(plan)

        # When the gate is enabled, DROP a signal whose regime favorability is an
        # AVAILABLE "unfavorable" label for its setup type (R10.2). Signals whose
        # regime is an Unavailable_Marker are RETAINED — never excluded on the
        # basis of regime (R10.6) — as are favorable/neutral signals. The drop
        # still advances the cooldown exactly as a taken signal would, so the
        # with-gate run walks the IDENTICAL history/rules as the without-gate run
        # and its seeded set is a strict SUBSET of the without-gate set (R10.4).
        gated_out = cfg.regime_gate_enabled and _signal_is_unfavorable(decision)

        # ── Relative-strength filter (with-filter run only) ──────────────────
        # When the filter is enabled, DROP a signal whose relative-strength
        # Alignment is an AVAILABLE "misaligned" label for its direction (R11.2).
        # Signals whose relative strength is an Unavailable_Marker are RETAINED —
        # never excluded on the basis of relative strength being unavailable
        # (R11.6) — as are aligned/neutral signals. The drop advances the cooldown
        # exactly as a taken signal would, mirroring the regime gate, so the
        # with-filter run walks the IDENTICAL history/rules as the without-filter
        # run and its seeded set is a strict SUBSET of the without-filter set.
        filtered_out = cfg.rs_filter_enabled and _signal_is_misaligned(decision)

        # ── Forecast filter (with-forecast run only) ─────────────────────────
        # When the forecast filter is enabled, DROP a signal whose
        # Forecast_Alignment is an AVAILABLE "misaligned" label for its direction
        # (R13.2). Signals whose forecast is an Unavailable_Marker are RETAINED —
        # never excluded on the basis of the forecast being unavailable (R13.4) —
        # as are aligned/neutral signals. The drop advances the cooldown exactly
        # as a taken signal would, mirroring the regime gate and RS filter, so the
        # with-forecast run walks the IDENTICAL history/rules as the
        # without-forecast run and its seeded set is a strict SUBSET of it.
        forecast_filtered_out = cfg.forecast_filter_enabled and _signal_is_forecast_misaligned(decision)

        # ── Session filter (with-filter run only) ────────────────────────────
        # When the session filter is enabled, DROP a signal whose Time_Favorability
        # is an AVAILABLE "unfavorable" label for its time window (R11.2). Signals
        # whose session result is an Unavailable_Marker are RETAINED — never
        # excluded on the basis of the session being unavailable (R11.5) — as are
        # favorable/neutral signals. The drop advances the cooldown exactly as a
        # taken signal would, mirroring the regime gate and the RS/forecast
        # filters, so the with-filter run walks the IDENTICAL history/rules as the
        # without-filter run and its seeded set is a strict SUBSET of it.
        session_filtered_out = cfg.session_filter_enabled and _signal_is_session_unfavorable(decision)

        if gated_out or filtered_out or forecast_filtered_out or session_filtered_out or (status == "expired" and not cfg.record_unresolved):
            cooldown_until = i + cfg.cooldown_bars
            continue
        results.append({
            "decision": decision,
            "status": status,
            "outcome_price": out_price,
            "outcome_at": out_at,
            "r_multiple": r_mult,
        })
        cooldown_until = i + cfg.cooldown_bars
    return results


def _fetch_candles(symbol: str, timeframe: str, limit: int) -> List[dict]:
    r = httpx.post(
        f"{RUST_SERVER_URL}/tools/get_candles",
        json={"symbol": symbol, "timeframe": timeframe, "limit": limit},
        timeout=20.0,
    )
    r.raise_for_status()
    data = r.json()
    if not isinstance(data, list):
        raise RuntimeError(f"Unexpected candle payload: {type(data).__name__}")
    return data


def _fetch_candles_questdb(symbol: str, timeframe: str, limit: int) -> List[dict]:
    """Read historical candles directly from QuestDB's HTTP query API.

    Daily/weekly timeframes come from ``historical_candles``; all other (intraday)
    timeframes from ``historical_intraday`` filtered by its ``timeframe`` column.
    ``CAST(ts AS LONG)`` yields microseconds since epoch (QuestDB's native unit),
    which we convert to the milliseconds the rest of the pipeline expects.
    ``ORDER BY ts LIMIT -N`` returns the most recent N rows in ascending order.
    """
    sym = symbol.replace("'", "''")  # escape for the SQL string literal
    tf = (timeframe or "").strip().lower()
    if tf in _DAILY_TIMEFRAMES:
        query = (
            "SELECT CAST(ts AS LONG) AS ts_us, open, high, low, close, volume "
            f"FROM historical_candles WHERE symbol='{sym}' ORDER BY ts LIMIT -{int(limit)}"
        )
    else:
        tf_lit = timeframe.replace("'", "''")
        query = (
            "SELECT CAST(ts AS LONG) AS ts_us, open, high, low, close, volume "
            f"FROM historical_intraday WHERE symbol='{sym}' AND timeframe='{tf_lit}' "
            f"ORDER BY ts LIMIT -{int(limit)}"
        )

    r = httpx.get(f"{QUESTDB_HTTP_URL}/exec", params={"query": query}, timeout=30.0)
    r.raise_for_status()
    body = r.json()
    if isinstance(body, dict) and body.get("error"):
        raise RuntimeError(f"QuestDB query error: {body.get('error')} (table may not exist or be empty)")
    dataset = body.get("dataset") if isinstance(body, dict) else None
    if not dataset:
        raise RuntimeError(
            f"QuestDB returned no rows for {symbol}/{timeframe}. "
            f"Has historical data been loaded for this symbol/timeframe?"
        )

    candles: List[dict] = []
    for row in dataset:
        if len(row) < 6 or row[0] is None:
            continue
        candles.append({
            "timestamp_ms": float(row[0]) / 1000.0,  # micros -> millis
            "open": row[1], "high": row[2], "low": row[3],
            "close": row[4], "volume": row[5] if row[5] is not None else 0.0,
        })
    return candles


def _resolve_candles(symbol: str, timeframe: str, limit: int, source: str) -> List[dict]:
    """Resolve candles from the requested source.

    ``auto`` (default) tries QuestDB first (works without the Tauri app), then
    falls back to the Rust tool server. ``questdb`` / ``server`` force one path.
    """
    if source == "questdb":
        return _fetch_candles_questdb(symbol, timeframe, limit)
    if source == "server":
        return _fetch_candles(symbol, timeframe, limit)
    # auto
    try:
        return _fetch_candles_questdb(symbol, timeframe, limit)
    except Exception as qe:
        print(f"[Backtest_Seeder] QuestDB source unavailable ({qe}); trying Rust tool server...")
        return _fetch_candles(symbol, timeframe, limit)


def _resolve_benchmark_candles(benchmark: str, timeframe: str, limit: int,
                               source: str) -> Optional[List[dict]]:
    """Resolve the Benchmark_Index candle series for a run.

    Mirrors how the symbol candles are resolved (``_resolve_candles`` for the
    benchmark symbol / same timeframe / same limit), so the relative-strength
    calculator compares like-for-like windows. Degrades to ``None`` on any
    retrieval failure (e.g. no history loaded for the benchmark) so the run still
    proceeds — relative strength then reports an honest Unavailable_Marker for
    every signal rather than aborting the seeding (R11.6, AD-4). Never raises.
    """
    if not isinstance(benchmark, str) or not benchmark.strip():
        return None
    try:
        return _resolve_candles(benchmark.strip(), timeframe, limit, source)
    except Exception as e:  # benchmark history may be absent — non-fatal.
        print(f"[Backtest_Seeder] benchmark candles for {benchmark!r} unavailable "
              f"({e}); relative strength will be reported as unavailable.")
        return None


def _load_candles_file(path: str) -> List[dict]:
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    if isinstance(data, dict) and isinstance(data.get("candles"), list):
        data = data["candles"]
    if not isinstance(data, list):
        raise RuntimeError("candles file must be a JSON list (or {\"candles\": [...]})")
    return data


def seed(symbol: str, timeframe: str, limit: int = 3000,
         candles: Optional[List[dict]] = None, cfg: Optional[BacktestConfig] = None,
         purge_first: bool = True, dry_run: bool = False, source: str = "auto") -> dict:
    """Generate, score, and (unless dry_run) write backtest trades to the journal.

    Returns a summary dict with the number of trades by outcome plus the
    resulting backtest-only stats from the journal.
    """
    cfg = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # Resolve the Benchmark_Index and its candle series once for the run so each
    # signal's relative strength is classified look-ahead-free against it (R11.1).
    benchmark = rs.resolve_benchmark(symbol)
    benchmark_candles = _resolve_benchmark_candles(benchmark, timeframe, limit, source)

    results = generate_and_score(
        candles, symbol, timeframe, cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )
    wins = sum(1 for r in results if r["status"] == "win")
    losses = sum(1 for r in results if r["status"] == "loss")
    expired = sum(1 for r in results if r["status"] == "expired")

    summary = {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "signals_scored": len(results),
        "wins": wins,
        "losses": losses,
        "expired": expired,
        "dry_run": dry_run,
    }

    if dry_run:
        summary["note"] = "dry-run: no journal writes performed"
        return summary

    if purge_first:
        removed = journal.purge(source="backtest", symbol=symbol)
        summary["purged_existing_backtest"] = removed

    written = 0
    for r in results:
        rid = journal.record_backtest_trade(
            r["decision"], symbol=symbol, timeframe=timeframe,
            status=r["status"], outcome_price=r["outcome_price"],
            outcome_at=r["outcome_at"], r_multiple=r["r_multiple"],
        )
        if rid is not None:
            written += 1
    summary["written"] = written
    summary["stats"] = journal.get_stats(symbol=symbol, source="backtest")
    return summary


# ── With-gate / without-gate comparison (R10.4, R10.7) ───────────────────────

def _run_metrics(results: List[dict]) -> dict:
    """Compute a single run's win-rate and expectancy over its CLOSED trades.

    A trade is *closed* when it resolved by hitting its stop or target — i.e.
    ``status`` is ``win`` or ``loss`` and carries a realized R-multiple. Expired
    (unresolved) trades are NOT closed and are excluded from both metrics.

      * win_rate   = winning closed trades / closed trades
      * expectancy = mean realized R-multiple per closed trade

    When a run has ZERO closed trades, BOTH metrics are reported as ``"n/a"``
    rather than computing a division by zero (R10.7).
    """
    closed = [r for r in results if r["status"] in ("win", "loss") and _is_num(r.get("r_multiple"))]
    n_closed = len(closed)
    if n_closed == 0:
        return {
            "closed_trades": 0,
            "winning_closed_trades": 0,
            "win_rate": "n/a",
            "expectancy": "n/a",
        }
    winning = sum(1 for r in closed if r["status"] == "win")
    expectancy = sum(r["r_multiple"] for r in closed) / n_closed
    return {
        "closed_trades": n_closed,
        "winning_closed_trades": winning,
        "win_rate": round(winning / n_closed, 4),
        "expectancy": round(expectancy, 4),
    }


def compare(symbol: str, timeframe: str, limit: int = 3000,
            candles: Optional[List[dict]] = None, cfg: Optional[BacktestConfig] = None,
            source: str = "auto") -> dict:
    """Run the backtest WITH and WITHOUT the regime gate and compare them (R10.4).

    Both runs use the IDENTICAL candle history and IDENTICAL setup rules — only
    ``regime_gate_enabled`` differs — so the two runs are directly comparable and
    the with-gate seeded set is a strict subset of the without-gate set (the gate
    only removes signals whose regime favorability is the available ``unfavorable``
    label; Unavailable_Marker signals are retained — R10.2, R10.6).

    Returns a summary reporting, for EACH run, the win-rate (winning closed /
    closed) and expectancy (mean realized R per closed trade), with ``"n/a"`` when
    a run produced zero closed trades (R10.7). Pure given ``candles`` — no journal
    writes are performed.
    """
    base = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # Identical history + identical rules; the gate flag is the ONLY difference.
    gated_cfg = replace(base, regime_gate_enabled=True)
    ungated_cfg = replace(base, regime_gate_enabled=False)

    with_gate = generate_and_score(candles, symbol, timeframe, gated_cfg)
    without_gate = generate_and_score(candles, symbol, timeframe, ungated_cfg)

    return {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "with_gate": {"signals_scored": len(with_gate), **_run_metrics(with_gate)},
        "without_gate": {"signals_scored": len(without_gate), **_run_metrics(without_gate)},
    }


# ── With-filter / without-filter comparison (R11.2, R11.4, R11.6, R11.7) ─────

def compare_relative_strength(symbol: str, timeframe: str, limit: int = 3000,
                              candles: Optional[List[dict]] = None,
                              benchmark_candles: Optional[List[dict]] = None,
                              cfg: Optional[BacktestConfig] = None,
                              benchmark: Optional[str] = None,
                              source: str = "auto") -> dict:
    """Run the backtest WITH and WITHOUT the relative-strength filter and compare (R11.4).

    Both runs use the IDENTICAL candle history, the IDENTICAL Benchmark_Index
    series, and IDENTICAL setup rules — only ``rs_filter_enabled`` differs — so
    the two runs are directly comparable and the with-filter seeded set is a
    strict subset of the without-filter set. The filter only removes signals whose
    relative-strength Alignment is the available ``misaligned`` label for their
    direction; signals whose relative strength is an Unavailable_Marker are
    RETAINED — never excluded on the basis of relative strength being unavailable
    (R11.2, R11.6).

    The Benchmark_Index and its candle series are resolved ONCE for the run (or
    supplied by the caller) so both runs classify relative strength look-ahead-free
    against the identical benchmark window (R11.1, R11.5). When no benchmark candle
    series is available, relative strength degrades to an honest Unavailable_Marker
    for every signal and the with-filter run retains all signals.

    Returns a summary reporting, for EACH run, the win-rate (winning closed /
    closed) and expectancy (mean realized R per closed trade), with ``"n/a"`` when
    a run produced zero closed trades (R11.7). Pure given ``candles`` /
    ``benchmark_candles`` — no journal writes are performed.
    """
    base = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # Resolve the Benchmark_Index and its candles ONCE so BOTH runs classify
    # relative strength against the IDENTICAL benchmark window (R11.1).
    if benchmark is None:
        benchmark = rs.resolve_benchmark(symbol)
    if benchmark_candles is None:
        benchmark_candles = _resolve_benchmark_candles(benchmark, timeframe, limit, source)

    # Identical history + identical rules; the filter flag is the ONLY difference.
    filtered_cfg = replace(base, rs_filter_enabled=True)
    unfiltered_cfg = replace(base, rs_filter_enabled=False)

    with_filter = generate_and_score(
        candles, symbol, timeframe, filtered_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )
    without_filter = generate_and_score(
        candles, symbol, timeframe, unfiltered_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )

    return {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "benchmark": benchmark,
        "with_filter": {"signals_scored": len(with_filter), **_run_metrics(with_filter)},
        "without_filter": {"signals_scored": len(without_filter), **_run_metrics(without_filter)},
    }


# ── With-session-filter / without-session-filter comparison (R11.2, R11.4, R11.5) ─

def compare_session(symbol: str, timeframe: str, limit: int = 3000,
                    candles: Optional[List[dict]] = None,
                    benchmark_candles: Optional[List[dict]] = None,
                    cfg: Optional[BacktestConfig] = None,
                    benchmark: Optional[str] = None,
                    source: str = "auto") -> dict:
    """Run the backtest WITH and WITHOUT the session filter and compare (R11.4).

    Both runs use the IDENTICAL candle history and IDENTICAL setup rules — only
    ``session_filter_enabled`` differs — so the two runs are directly comparable
    and the with-filter seeded set is a strict subset of the without-filter set.
    The filter only removes signals whose Time_Favorability is the available
    ``unfavorable`` label for their time window; signals whose session result is
    an Unavailable_Marker are RETAINED — never excluded on the basis of the
    session being unavailable (R11.2, R11.5).

    Each signal's session is classified look-ahead-free from the timestamp of its
    OWN candle via the same ``session.classify_session`` the live tool path uses
    (R11.1, R11.6). The session filter needs no benchmark, but
    ``generate_and_score`` also labels relative strength for every signal, so the
    Benchmark_Index and its candle series are resolved ONCE for the run (as in
    ``compare_relative_strength``) and passed to BOTH runs, keeping each run
    well-formed and identical apart from the session-filter flag.

    Returns a summary reporting, for EACH run, the win-rate (winning closed /
    closed) and expectancy (mean realized R per closed trade), with ``"n/a"`` when
    a run produced zero closed trades (R11.4). Pure given ``candles`` /
    ``benchmark_candles`` — no journal writes are performed.
    """
    base = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # The session filter needs no benchmark, but generate_and_score labels
    # relative strength regardless; resolve the Benchmark_Index and its candles
    # ONCE so BOTH runs are well-formed and identical apart from the flag.
    if benchmark is None:
        benchmark = rs.resolve_benchmark(symbol)
    if benchmark_candles is None:
        benchmark_candles = _resolve_benchmark_candles(benchmark, timeframe, limit, source)

    # Identical history + identical rules; the session-filter flag is the ONLY difference.
    filtered_cfg = replace(base, session_filter_enabled=True)
    unfiltered_cfg = replace(base, session_filter_enabled=False)

    with_filter = generate_and_score(
        candles, symbol, timeframe, filtered_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )
    without_filter = generate_and_score(
        candles, symbol, timeframe, unfiltered_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )

    return {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "benchmark": benchmark,
        "with_filter": {"signals_scored": len(with_filter), **_run_metrics(with_filter)},
        "without_filter": {"signals_scored": len(without_filter), **_run_metrics(without_filter)},
    }


# ── With-forecast / without-forecast comparison (R13.2, R13.3, R13.4) ────────

def compare_forecast(symbol: str, timeframe: str, limit: int = 3000,
                     candles: Optional[List[dict]] = None,
                     cfg: Optional[BacktestConfig] = None,
                     source: str = "auto") -> dict:
    """Run the backtest WITH and WITHOUT the forecast filter and compare (R13.3).

    Both runs use the IDENTICAL candle history and IDENTICAL setup rules — only
    ``forecast_filter_enabled`` differs — so the two runs are directly comparable
    and the with-forecast seeded set is a strict subset of the without-forecast
    set. The filter only removes signals whose Forecast_Alignment is the available
    ``misaligned`` label for their direction; signals whose forecast is an
    Unavailable_Marker are RETAINED — never excluded on the basis of the forecast
    being unavailable (R13.2, R13.4).

    The forecaster needs no benchmark, but ``generate_and_score`` also labels
    relative strength for every signal, so the Benchmark_Index and its candle
    series are resolved ONCE for the run (as in ``compare_relative_strength``) and
    passed to BOTH runs, keeping each run well-formed and identical apart from the
    forecast-filter flag.

    Returns a summary reporting, for EACH run, the win-rate (winning closed /
    closed) and expectancy (mean realized R per closed trade), with ``"n/a"`` when
    a run produced zero closed trades (R13.3). Pure given ``candles`` — no journal
    writes are performed.
    """
    base = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # The forecast filter needs no benchmark, but generate_and_score labels
    # relative strength regardless; resolve the Benchmark_Index and its candles
    # ONCE so BOTH runs are well-formed and identical apart from the flag.
    benchmark = rs.resolve_benchmark(symbol)
    benchmark_candles = _resolve_benchmark_candles(benchmark, timeframe, limit, source)

    # Identical history + identical rules; the forecast-filter flag is the ONLY difference.
    filtered_cfg = replace(base, forecast_filter_enabled=True)
    unfiltered_cfg = replace(base, forecast_filter_enabled=False)

    with_forecast = generate_and_score(
        candles, symbol, timeframe, filtered_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )
    without_forecast = generate_and_score(
        candles, symbol, timeframe, unfiltered_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )

    return {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "with_forecast": {"signals_scored": len(with_forecast), **_run_metrics(with_forecast)},
        "without_forecast": {"signals_scored": len(without_forecast), **_run_metrics(without_forecast)},
    }


# ── Managed / unmanaged comparison (R12.1–R12.5) ─────────────────────────────

def _management_run_metrics(results: List[dict]) -> dict:
    """Compute a single run's win-rate, expectancy, and downside over CLOSED trades.

    A trade is *closed* when it resolved by hitting a target or its stop — i.e.
    ``status`` is ``win`` or ``loss`` and carries a realized R-multiple (for a
    managed run this is the multi-leg ``Realized_R`` the Trade_Manager computed,
    for an unmanaged run it is the single-target R). Expired (unresolved / open)
    trades are NOT closed and are excluded from every metric.

      * win_rate   = positive-Realized_R closed trades / closed trades (R12.2)
      * expectancy = mean Realized_R per closed trade (R12.2)
      * downside   = mean Realized_R of the LOSING closed trades — the risk-shape
        measure so management's effect on the downside is visible, not only the
        mean (R12.3). Reported as ``"n/a"`` when a run has closed trades but none
        of them are losers (no losing population to average).

    When a run has ZERO closed trades, ALL metrics are reported as the ``"n/a"``
    sentinel rather than dividing by zero (R12.4) — the same convention as
    ``_run_metrics``. A *winner* is a strictly-positive Realized_R and a *loser*
    is a non-positive Realized_R, matching the journal/backtest win/loss
    convention (R6.4).
    """
    closed = [r for r in results if r["status"] in ("win", "loss") and _is_num(r.get("r_multiple"))]
    n_closed = len(closed)
    if n_closed == 0:
        return {
            "closed_trades": 0,
            "winning_closed_trades": 0,
            "losing_closed_trades": 0,
            "win_rate": "n/a",
            "expectancy": "n/a",
            "downside": "n/a",
        }
    winners = [r for r in closed if r["r_multiple"] > 0]
    losers = [r for r in closed if r["r_multiple"] <= 0]
    expectancy = sum(r["r_multiple"] for r in closed) / n_closed
    # Mean Realized_R of the losing population — "n/a" when there are no losers
    # (an empty population has no mean; never divide by zero).
    downside = (sum(r["r_multiple"] for r in losers) / len(losers)) if losers else "n/a"
    return {
        "closed_trades": n_closed,
        "winning_closed_trades": len(winners),
        "losing_closed_trades": len(losers),
        "win_rate": round(len(winners) / n_closed, 4),
        "expectancy": round(expectancy, 4),
        "downside": round(downside, 4) if _is_num(downside) else downside,
    }


def compare_management(symbol: str, timeframe: str, limit: int = 3000,
                       candles: Optional[List[dict]] = None,
                       benchmark_candles: Optional[List[dict]] = None,
                       cfg: Optional[BacktestConfig] = None,
                       benchmark: Optional[str] = None,
                       source: str = "auto") -> dict:
    """Run the backtest UNMANAGED and MANAGED over identical signals and compare (R12.1).

    Both runs walk the IDENTICAL candle history with the IDENTICAL setup rules and
    the IDENTICAL Benchmark_Index series — only ``manage_trades`` differs — so the
    two runs score the SAME generated signal set twice (R12.1):

      * the unmanaged run (``manage_trades=False``) scores every signal as a
        Single_Target_Trade on the legacy conservative ``_score_signal`` path, and
      * the managed run (``manage_trades=True``) attaches the uniform default
        Management_Plan built from the configured ``trade_manager`` defaults to
        every signal and scores it with ``trade_manager.simulate_plan`` (R12.5) —

    both via the SAME ``generate_and_score`` / SAME ``Trade_Manager`` (AD-2): the
    managed-vs-unmanaged math is never reimplemented here, only the candle window
    and the plan differ.

    The Benchmark_Index and its candle series are resolved ONCE for the run (or
    supplied by the caller) because ``generate_and_score`` labels relative strength
    for every signal regardless of management; passing the identical benchmark
    window to both runs keeps each run well-formed and identical apart from the
    ``manage_trades`` flag (R11.1, mirrors ``compare_forecast`` /
    ``compare_relative_strength``).

    Returns a summary reporting, for EACH run, the win-rate (positive-Realized_R
    closed trades / closed trades), the expectancy (mean Realized_R per closed
    trade), and a downside measure (mean Realized_R of losing closed trades), with
    ``"n/a"`` when a run produced zero closed trades (R12.2, R12.3, R12.4). Pure
    given ``candles`` / ``benchmark_candles`` — no journal writes are performed.
    """
    base = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # Resolve the Benchmark_Index and its candles ONCE so BOTH runs label
    # relative strength against the IDENTICAL benchmark window (R11.1).
    if benchmark is None:
        benchmark = rs.resolve_benchmark(symbol)
    if benchmark_candles is None:
        benchmark_candles = _resolve_benchmark_candles(benchmark, timeframe, limit, source)

    # Identical history + identical rules; the manage_trades flag is the ONLY
    # difference. The managed run's plan is the uniform configured default applied
    # to every signal by generate_and_score (R12.5); the unmanaged run keeps the
    # single-target bracket. Both score via the SAME Trade_Manager (AD-2).
    managed_cfg = replace(base, manage_trades=True)
    unmanaged_cfg = replace(base, manage_trades=False)

    unmanaged = generate_and_score(
        candles, symbol, timeframe, unmanaged_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )
    managed = generate_and_score(
        candles, symbol, timeframe, managed_cfg,
        benchmark_candles=benchmark_candles, benchmark=benchmark,
    )

    return {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": len(candles),
        "benchmark": benchmark,
        "unmanaged": {"signals_scored": len(unmanaged), **_management_run_metrics(unmanaged)},
        "managed": {"signals_scored": len(managed), **_management_run_metrics(managed)},
    }


# ── Calibration (reliability) measurement (R12.1–R12.5) ──────────────────────

# Sentinel reported for a probability bin that contains zero recorded forecasts.
# An empty bin has no mean predicted probability and no realized fraction, so we
# report this string rather than dividing by zero (R12.4). The scalar
# ``calibration_error`` uses the same sentinel when EVERY bin is empty (no
# non-empty bin to average over).
_CALIBRATION_NA = "n/a"


def _calibration_from_records(records, bins) -> dict:
    """Bin (Up_Probability, realized-up) records and report reliability stats.

    ``records`` is a list of ``{"up_probability": float in [0, 1],
    "went_up": bool}`` dicts. The ``[0, 1]`` probability range is partitioned into
    ``bins`` equal-width bins; a record is placed in bin
    ``min(int(up_probability * bins), bins - 1)`` so the ``up_probability == 1.0``
    edge falls in the LAST bin rather than overflowing (R12.2).

    For each NON-EMPTY bin we report its ``count``, the ``mean_predicted`` (mean
    of the bin's ``up_probability`` values), and the ``realized_up_fraction`` (the
    fraction of the bin's records whose ``went_up`` is True) — R12.2. Each EMPTY
    bin is reported with ``count`` 0 and ``mean_predicted`` / ``realized_up_fraction``
    set to the ``"n/a"`` sentinel rather than dividing by zero (R12.4).

    ``calibration_error`` is the mean absolute difference between
    ``mean_predicted`` and ``realized_up_fraction`` over the NON-EMPTY bins
    (R12.3); when every bin is empty it is the same ``"n/a"`` sentinel (no
    non-empty bin to average). ``total_records`` is the number of valid records
    binned.

    Pure (no input mutation), never divides by zero, and never raises — a
    non-list ``records``, malformed record dicts, out-of-range/non-finite
    probabilities, and a non-positive/garbage ``bins`` are all tolerated by
    coercion and skipping.
    """
    # Coerce the bin count to a positive integer; anything unparseable or < 1
    # collapses to a single [0, 1] bin so the partition is always well-formed.
    try:
        n_bins = int(bins)
    except (TypeError, ValueError):
        n_bins = 0
    if n_bins < 1:
        n_bins = 1

    counts = [0] * n_bins
    prob_sums = [0.0] * n_bins
    up_counts = [0] * n_bins
    total = 0

    for rec in records if isinstance(records, list) else []:
        if not isinstance(rec, dict):
            continue
        p = rec.get("up_probability")
        # Only finite probabilities inside [0, 1] are binnable.
        if not _is_num(p) or p < 0.0 or p > 1.0:
            continue
        idx = int(p * n_bins)
        if idx >= n_bins:           # the up_probability == 1.0 edge lands here
            idx = n_bins - 1
        elif idx < 0:               # defensive; p >= 0 already guaranteed
            idx = 0
        counts[idx] += 1
        prob_sums[idx] += p
        if bool(rec.get("went_up")):
            up_counts[idx] += 1
        total += 1

    width = 1.0 / n_bins
    bins_report = []
    abs_errors = []
    for k in range(n_bins):
        lower = round(k * width, 10)
        upper = round((k + 1) * width, 10)
        if counts[k] == 0:
            bins_report.append({
                "lower": lower,
                "upper": upper,
                "count": 0,
                "mean_predicted": _CALIBRATION_NA,
                "realized_up_fraction": _CALIBRATION_NA,
            })
            continue
        mean_predicted = prob_sums[k] / counts[k]
        realized_up_fraction = up_counts[k] / counts[k]
        abs_errors.append(abs(mean_predicted - realized_up_fraction))
        bins_report.append({
            "lower": lower,
            "upper": upper,
            "count": counts[k],
            "mean_predicted": round(mean_predicted, 6),
            "realized_up_fraction": round(realized_up_fraction, 6),
        })

    calibration_error = (
        round(sum(abs_errors) / len(abs_errors), 6) if abs_errors else _CALIBRATION_NA
    )
    return {
        "bins": bins_report,
        "calibration_error": calibration_error,
        "total_records": total,
    }


def calibrate_forecast(symbol: str, timeframe: str, limit: int = 3000,
                       candles: Optional[List[dict]] = None,
                       cfg: Optional[BacktestConfig] = None,
                       bins: Optional[int] = None,
                       source: str = "auto") -> dict:
    """Measure whether the forecaster's Up_Probability matches realized outcomes.

    Walks the candle history and, for every bar ``i`` that has a valid next bar
    ``i + 1``, computes the forecast from ONLY ``candles[: i + 1]`` (the window at
    or before bar ``i`` — no look-ahead, R12.1) via the SAME ``forecaster.forecast``
    the live tool path uses (R12.5; the calibration never reimplements the forecast
    math). When that produces a usable Forecast_Label with a finite Up_Probability,
    the predicted probability is paired with the realized direction of the next bar
    — ``went_up = close_{i+1} > close_i`` (R12.1) — and collected as a record.
    Bars whose forecast is an Unavailable_Marker (e.g. insufficient early history)
    or whose adjacent closes are non-numeric are skipped.

    The records are passed to ``_calibration_from_records`` with ``bins`` (or the
    resolved ``prob_bins`` default when not supplied), and the per-bin report,
    scalar calibration error, and paired-record count are returned alongside the
    run's ``symbol`` / ``timeframe`` / ``candles`` context. Pure given ``candles``
    (no journal writes); the forecaster never touches the network.
    """
    cfg = cfg or BacktestConfig()
    if candles is None:
        candles = _resolve_candles(symbol, timeframe, limit, source)

    # Resolve the forecaster parameters ONCE, reusing the SAME resolver the live
    # get_forecast tool and the backtest comparison use (R12.5, R14.5).
    fc_config = forecaster.resolve_forecaster_config()

    n = len(candles) if isinstance(candles, list) else 0
    records: List[dict] = []
    for i in range(n - 1):
        cur = candles[i]
        nxt = candles[i + 1]
        cur_close = cur.get("close") if isinstance(cur, dict) else None
        nxt_close = nxt.get("close") if isinstance(nxt, dict) else None
        # Guard non-numeric closes — the realized direction is undefined without
        # two finite closes (R12.1).
        if not (_is_num(cur_close) and _is_num(nxt_close)):
            continue

        # Forecast from ONLY candles at or before bar i — the point-in-time slice
        # candles[: i + 1] carries no later candles, so there is no look-ahead
        # (R12.1). The same forecaster as the live tool path (R12.5).
        fc_result = forecaster.forecast(
            candles[: i + 1], fc_config, symbol=symbol, timeframe=timeframe,
        )
        if not isinstance(fc_result, dict) or fc_result.get("unavailable") is True:
            continue
        up_probability = fc_result.get("up_probability")
        if not _is_num(up_probability):
            continue

        # Pair the predicted Up_Probability with the realized next-bar direction.
        records.append({
            "up_probability": up_probability,
            "went_up": nxt_close > cur_close,
        })

    report = _calibration_from_records(records, bins or fc_config.prob_bins)
    return {
        "symbol": symbol,
        "timeframe": timeframe,
        "candles": n,
        **report,
    }


# ── Discovery & batch seeding ─────────────────────────────────────────────────

def discover_symbols(source: str = "questdb") -> List[str]:
    """Return every symbol present in the QuestDB archive (daily ∪ intraday)."""
    symbols = set()
    for table in ("historical_candles", "historical_intraday"):
        try:
            r = httpx.get(
                f"{QUESTDB_HTTP_URL}/exec",
                params={"query": f"SELECT DISTINCT symbol FROM {table}"},
                timeout=15.0,
            )
            r.raise_for_status()
            body = r.json()
            for row in body.get("dataset", []) or []:
                if row and row[0]:
                    symbols.add(row[0])
        except Exception as e:
            print(f"[Backtest_Seeder] symbol discovery from {table} failed: {e}")
    return sorted(symbols)


def discover_intraday_timeframes() -> List[str]:
    """Return the distinct intraday timeframe labels stored in QuestDB."""
    try:
        r = httpx.get(
            f"{QUESTDB_HTTP_URL}/exec",
            params={"query": "SELECT DISTINCT timeframe FROM historical_intraday"},
            timeout=15.0,
        )
        r.raise_for_status()
        body = r.json()
        tfs = [row[0] for row in body.get("dataset", []) or [] if row and row[0]]
        return sorted(tfs)
    except Exception as e:
        print(f"[Backtest_Seeder] intraday timeframe discovery failed: {e}")
        return []


def seed_batch(symbols: List[str], timeframes: List[str], limit: int = 3000,
               cfg: Optional[BacktestConfig] = None, purge_first: bool = True,
               dry_run: bool = False, source: str = "auto") -> dict:
    """Seed every (symbol × timeframe) combination.

    Purges existing backtest rows ONCE per symbol (covering all its timeframes)
    before seeding, so re-runs stay idempotent without wiping earlier timeframes
    mid-batch. Each cell is isolated: a failure (e.g. no data for that
    symbol/timeframe) is recorded and the batch continues.
    """
    cfg = cfg or BacktestConfig()
    cells = []
    totals = {"signals_scored": 0, "wins": 0, "losses": 0, "written": 0, "errors": 0}

    for sym in symbols:
        if purge_first and not dry_run:
            removed = journal.purge(source="backtest", symbol=sym)
            if removed:
                print(f"[Backtest_Seeder] purged {removed} existing backtest row(s) for {sym}.")
        for tf in timeframes:
            try:
                res = seed(sym, tf, limit=limit, cfg=cfg, purge_first=False,
                           dry_run=dry_run, source=source)
                cells.append({
                    "symbol": sym, "timeframe": tf,
                    "signals_scored": res.get("signals_scored", 0),
                    "wins": res.get("wins", 0), "losses": res.get("losses", 0),
                    "written": res.get("written", 0),
                })
                totals["signals_scored"] += res.get("signals_scored", 0)
                totals["wins"] += res.get("wins", 0)
                totals["losses"] += res.get("losses", 0)
                totals["written"] += res.get("written", 0)
                print(f"[Backtest_Seeder] {sym}/{tf}: {res.get('signals_scored',0)} scored "
                      f"({res.get('wins',0)}W/{res.get('losses',0)}L), {res.get('written',0)} written.")
            except Exception as e:
                totals["errors"] += 1
                cells.append({"symbol": sym, "timeframe": tf, "error": str(e)})
                print(f"[Backtest_Seeder] {sym}/{tf}: SKIPPED ({e})")

    scored = totals["wins"] + totals["losses"]
    return {
        "symbols": len(symbols),
        "timeframes": timeframes,
        "totals": totals,
        "overall_win_rate": round(totals["wins"] / scored, 4) if scored else None,
        "dry_run": dry_run,
        "cells": cells,
    }


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(description="Seed the Trade_Journal from historical candles.")
    p.add_argument("--symbol", default=None, help="Trading symbol, e.g. RELIANCE (omit with --all-symbols)")
    p.add_argument("--all-symbols", action="store_true", help="Seed every symbol found in the QuestDB archive")
    p.add_argument("--timeframe", default="1d",
                   help="Timeframe(s), comma-separated (e.g. '1d,15m,1h'). Default 1d")
    p.add_argument("--all-timeframes", action="store_true",
                   help="Seed 1d plus every intraday timeframe present in QuestDB")
    p.add_argument("--limit", type=int, default=3000, help="Candles to fetch per symbol/timeframe")
    p.add_argument("--source", choices=["auto", "questdb", "server"], default="auto",
                   help="Candle source: auto (QuestDB then tool server), questdb, or server")
    p.add_argument("--candles-file", default=None,
                   help="Load candles from a JSON file (single symbol/timeframe only)")
    p.add_argument("--no-purge", action="store_true", help="Do not purge existing backtest rows first")
    p.add_argument("--dry-run", action="store_true", help="Compute and print stats without writing to the journal")

    # ── Rule tuning knobs ────────────────────────────────────────────────────
    p.add_argument("--rr", type=float, default=None, help="Risk:Reward multiple (target = RR x stop). Default 2.0")
    p.add_argument("--atr-mult", type=float, default=None, help="Stop distance as a multiple of ATR. Default 1.5")
    p.add_argument("--horizon", type=int, default=None, help="Max bars to let a trade resolve. Default 200")
    p.add_argument("--cooldown", type=int, default=None, help="Min bars between successive signals. Default 5")
    p.add_argument("--lookback", type=int, default=None, help="Bars of context per decision. Default 120")
    p.add_argument("--record-expired", action="store_true",
                   help="Also record trades that never hit stop/target (as 'expired')")
    args = p.parse_args()

    # Build the config from any provided knobs (unset → dataclass defaults).
    cfg = BacktestConfig()
    if args.rr is not None:
        cfg.risk_reward = args.rr
    if args.atr_mult is not None:
        cfg.atr_stop_mult = args.atr_mult
    if args.horizon is not None:
        cfg.max_horizon_bars = args.horizon
    if args.cooldown is not None:
        cfg.cooldown_bars = args.cooldown
    if args.lookback is not None:
        cfg.lookback = args.lookback
    if args.record_expired:
        cfg.record_unresolved = True

    # Resolve the timeframe list.
    if args.all_timeframes:
        timeframes = ["1d"] + [tf for tf in discover_intraday_timeframes() if tf.lower() not in _DAILY_TIMEFRAMES]
    else:
        timeframes = [tf.strip() for tf in args.timeframe.split(",") if tf.strip()]
    if not timeframes:
        print("[Backtest_Seeder] No timeframes resolved.")
        raise SystemExit(1)

    # ── Single-symbol file mode (kept simple: one symbol, one timeframe) ─────
    if args.candles_file:
        if not args.symbol:
            print("[Backtest_Seeder] --candles-file requires --symbol.")
            raise SystemExit(1)
        candles = _load_candles_file(args.candles_file)
        summary = seed(args.symbol, timeframes[0], limit=args.limit, candles=candles,
                       cfg=cfg, purge_first=not args.no_purge, dry_run=args.dry_run)
        print("\n[Backtest_Seeder] Summary:")
        print(json.dumps(summary, indent=2))
        return

    # ── Resolve the symbol list ──────────────────────────────────────────────
    if args.all_symbols:
        symbols = discover_symbols(args.source)
        if not symbols:
            print("[Backtest_Seeder] No symbols discovered in QuestDB.")
            raise SystemExit(1)
        print(f"[Backtest_Seeder] Discovered {len(symbols)} symbol(s): {', '.join(symbols)}")
    elif args.symbol:
        symbols = [args.symbol]
    else:
        print("[Backtest_Seeder] Provide --symbol or --all-symbols.")
        raise SystemExit(1)

    # ── Single symbol + single timeframe → detailed per-setup summary ────────
    if len(symbols) == 1 and len(timeframes) == 1:
        try:
            summary = seed(symbols[0], timeframes[0], limit=args.limit, cfg=cfg,
                           purge_first=not args.no_purge, dry_run=args.dry_run, source=args.source)
        except Exception as e:
            print(f"[Backtest_Seeder] FAILED: {e}")
            raise SystemExit(1)
        print("\n[Backtest_Seeder] Summary:")
        print(json.dumps(summary, indent=2))
        return

    # ── Batch mode (multi-symbol and/or multi-timeframe) ─────────────────────
    summary = seed_batch(symbols, timeframes, limit=args.limit, cfg=cfg,
                         purge_first=not args.no_purge, dry_run=args.dry_run, source=args.source)
    print("\n[Backtest_Seeder] Batch Summary:")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
