import React from 'react';
import {
  Crosshair,
  TrendingUp,
  Minus,
  Brush,
  Type,
  Ruler,
  Circle,
  MousePointer2,
  Eraser,
  ArrowRight,
  Plus,
  AlignEndHorizontal,
  AlignCenterHorizontal,
  Layers,
  Clock,
  Wind,
  Timer,
  Target,
  RotateCcw,
  Sparkles,
  Triangle,
  Waypoints,
  Grid3x3,
  Scan,
  Hash,
  Fan,
  Hexagon,
  Pentagon,
  Gem,
  Diamond,
  Shapes,
  GitBranch,
  GitMerge,
  GitPullRequest,
  GitCommit,
  Workflow,
  BarChart3,
  AudioWaveform,
  Waves,
  MapPin,
  Navigation,
  ArrowBigUp,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  Square,
  RotateCw,
  PenTool,
  Orbit,
  Spline,
  Slice,
  Sigma,
  Radical,
  Anchor,
  StickyNote,
  MessageSquare,
  MessageCircle,
  Tag,
  Monitor,
  Signpost,
  Flag,
  ArrowUpRight,
  ArrowDownRight,
  LineChart,
  BarChart2,
  Rss,
  BarChart4,
  Calendar,
  CalendarRange,
  MoveRight,
  Info,
  MoveHorizontal,
  CornerRightUp,
  Columns,
  TrendingDown,
  ChevronsUpDown,
  Unlink,
  Highlighter,
  MoveVertical
} from 'lucide-react';
import { type ToolMenuEntry } from './ToolMenu';

export const cursorOptions = [
  { id: 'cross', label: 'Crosshair', icon: Crosshair },
  { id: 'dot', label: 'Dot', icon: Circle },
  { id: 'arrow', label: 'Arrow', icon: MousePointer2 },
  { id: 'eraser', label: 'Eraser', icon: Eraser },
];

export const lineOptions: ToolMenuEntry[] = [
  { id: 'trendline', label: 'Trend Line', icon: TrendingUp, shortcut: 'Alt + T' },
  { id: 'ray', label: 'Ray', icon: MoveRight },
  { id: 'info-line', label: 'Info Line', icon: Info },
  { id: 'extended-line', label: 'Extended Line', icon: MoveHorizontal },
  { id: 'trend-angle', label: 'Trend Angle', icon: CornerRightUp },
  { id: 'horizontal-line', label: 'Horizontal Line', icon: Minus, shortcut: 'Alt + H' },
  { id: 'horizontal-ray', label: 'Horizontal Ray', icon: ArrowRight, shortcut: 'Alt + J' },
  { id: 'vertical-line', label: 'Vertical Line', icon: MoveVertical, shortcut: 'Alt + V' },
  { id: 'cross-line', label: 'Cross Line', icon: Plus, shortcut: 'Alt + C' },
  { section: 'Channels' },
  { id: 'parallel-channel', label: 'Parallel Channel', icon: Columns },
  { id: 'regression-trend', label: 'Regression Trend', icon: TrendingDown },
  { id: 'flat-top-bottom', label: 'Flat Top/Bottom', icon: ChevronsUpDown },
  { id: 'disjoint-channel', label: 'Disjoint Channel', icon: Unlink },
];

export const fibOptions: ToolMenuEntry[] = [
  { section: 'Fibonacci' },
  { id: 'fib-retracement', label: 'Fib Retracement', icon: AlignEndHorizontal, shortcut: 'Alt + F' },
  { id: 'fib-extension', label: 'Trend-Based Fib Extension', icon: AlignCenterHorizontal },
  { id: 'fib-channel', label: 'Fib Channel', icon: Layers },
  { id: 'fib-time-zone', label: 'Fib Time Zone', icon: Clock },
  { id: 'fib-speed-fan', label: 'Fib Speed Resistance Fan', icon: Wind },
  { id: 'fib-time-trend', label: 'Trend-Based Fib Time', icon: Timer },
  { id: 'fib-circles', label: 'Fib Circles', icon: Target },
  { id: 'fib-spiral', label: 'Fib Spiral', icon: RotateCcw },
  { id: 'fib-arcs', label: 'Fib Speed Resistance Arcs', icon: Sparkles },
  { id: 'fib-wedge', label: 'Fib Wedge', icon: Triangle },
  { id: 'pitchfan', label: 'Pitchfan', icon: Waypoints },
  { section: 'Gann' },
  { id: 'gann-box', label: 'Gann Box', icon: Grid3x3 },
  { id: 'gann-square-fixed', label: 'Gann Square Fixed', icon: Scan },
  { id: 'gann-square', label: 'Gann Square', icon: Hash },
  { id: 'gann-fan', label: 'Gann Fan', icon: Fan },
];

export const patternOptions: ToolMenuEntry[] = [
  { section: 'Patterns' },
  { id: 'xabcd-pattern', label: 'XABCD Pattern', icon: Hexagon },
  { id: 'cypher-pattern', label: 'Cypher Pattern', icon: Pentagon },
  { id: 'head-shoulders', label: 'Head and Shoulders', icon: Gem },
  { id: 'abcd-pattern', label: 'ABCD Pattern', icon: Diamond },
  { id: 'triangle-pattern', label: 'Triangle Pattern', icon: Triangle },
  { id: 'three-drives', label: 'Three Drives Pattern', icon: Shapes },
  { section: 'Elliott Waves' },
  { id: 'elliott-impulse', label: 'Elliott Impulse Wave (12345)', icon: GitBranch },
  { id: 'elliott-correction', label: 'Elliott Correction Wave (ABC)', icon: GitMerge },
  { id: 'elliott-triangle', label: 'Elliott Triangle Wave (ABCDE)', icon: GitPullRequest },
  { id: 'elliott-double-combo', label: 'Elliott Double Combo (WXY)', icon: GitCommit },
  { id: 'elliott-triple-combo', label: 'Elliott Triple Combo (WXYXZ)', icon: Workflow },
  { section: 'Cycles' },
  { id: 'cyclic-lines', label: 'Cyclic Lines', icon: BarChart3 },
  { id: 'time-cycles', label: 'Time Cycles', icon: AudioWaveform },
  { id: 'sine-line', label: 'Sine Line', icon: Waves },
];

export const shapeOptions: ToolMenuEntry[] = [
  { section: 'Brushes' },
  { id: 'brush', label: 'Brush', icon: Brush },
  { id: 'highlighter', label: 'Highlighter', icon: Highlighter },
  { section: 'Arrows' },
  { id: 'arrow-marker', label: 'Arrow Marker', icon: MapPin },
  { id: 'arrow', label: 'Arrow', icon: Navigation },
  { id: 'arrow-mark-up', label: 'Arrow Mark Up', icon: ArrowBigUp },
  { id: 'arrow-mark-down', label: 'Arrow Mark Down', icon: ArrowBigDown },
  { id: 'arrow-mark-left', label: 'Arrow Mark Left', icon: ArrowBigLeft },
  { id: 'arrow-mark-right', label: 'Arrow Mark Right', icon: ArrowBigRight },
  { section: 'Shapes' },
  { id: 'rectangle', label: 'Rectangle', icon: Square, shortcut: 'Alt + Shift + R' },
  { id: 'rotated-rectangle', label: 'Rotated Rectangle', icon: RotateCw },
  { id: 'path', label: 'Path', icon: PenTool },
  { id: 'circle', label: 'Circle', icon: Circle },
  { id: 'ellipse', label: 'Ellipse', icon: Orbit },
  { id: 'polyline', label: 'Polyline', icon: Spline },
  { id: 'triangle-shape', label: 'Triangle', icon: Triangle },
  { id: 'arc', label: 'Arc', icon: Slice },
  { id: 'curve', label: 'Curve', icon: Sigma },
  { id: 'double-curve', label: 'Double Curve', icon: Radical },
];

export const textOptions: ToolMenuEntry[] = [
  { section: 'Text & Notes' },
  { id: 'text', label: 'Text', icon: Type },
  { id: 'anchored-text', label: 'Anchored Text', icon: Anchor },
  { id: 'note', label: 'Note', icon: StickyNote },
  { id: 'anchored-note', label: 'Anchored Note', icon: MapPin },
  { id: 'callout', label: 'Callout', icon: MessageSquare },
  { id: 'comment', label: 'Comment', icon: MessageCircle },
  { id: 'price-label', label: 'Price Label', icon: Tag },
  { id: 'price-note', label: 'Price Note', icon: Monitor },
  { id: 'signpost', label: 'Signpost', icon: Signpost },
  { id: 'flag-mark', label: 'Flag Mark', icon: Flag },
];

export const projectionOptions: ToolMenuEntry[] = [
  { section: 'Projection' },
  { id: 'long-position', label: 'Long Position', icon: ArrowUpRight },
  { id: 'short-position', label: 'Short Position', icon: ArrowDownRight },
  { id: 'forecast', label: 'Forecast', icon: LineChart },
  { id: 'bars-pattern', label: 'Bars Pattern', icon: BarChart2 },
  { id: 'ghost-feed', label: 'Ghost Feed', icon: Rss },
  { id: 'projection', label: 'Projection', icon: TrendingUp },
  { section: 'Volume-Based' },
  { id: 'anchored-vwap', label: 'Anchored VWAP', icon: Anchor },
  { id: 'fixed-range-volume', label: 'Fixed Range Volume Profile', icon: BarChart4 },
  { section: 'Measurer' },
  { id: 'price-range', label: 'Price Range', icon: Ruler },
  { id: 'date-range', label: 'Date Range', icon: Calendar },
  { id: 'date-price-range', label: 'Date and Price Range', icon: CalendarRange },
];
