use reqwest::Client;
use serde_json::{json, Value};
use std::env;
use std::error::Error;

pub struct LlmClient {
    client: Client,
    api_key: String,
}

impl LlmClient {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let api_key = env::var("GEMINI_API_KEY")
            .map_err(|_| "GEMINI_API_KEY environment variable is not set")?;
        Ok(Self {
            client: Client::new(),
            api_key,
        })
    }

    pub async fn generate_insight(&self, symbol: &str, price_change_pct: f64) -> Result<(String, String, i32), Box<dyn Error>> {
        let url = format!(
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={}",
            self.api_key
        );

        let payload = json!({
            "systemInstruction": {
                "parts": [{ "text": "You are an elite quantitative analyst. Provide a 2-sentence explanation for a market anomaly. You MUST return a raw JSON object with exactly three keys: 'headline' (string), 'analysis' (string), and 'sentiment' (integer 1-100, where 1 is bearish and 100 is bullish)." }]
            },
            "contents": [{
                "parts": [{ "text": format!("Generate a rapid analysis for {} which just moved {}%.", symbol, price_change_pct) }]
            }],
            "generationConfig": {
                "responseMimeType": "application/json"
            }
        });

        let response = self.client.post(&url).json(&payload).send().await?;

        if !response.status().is_success() {
            let error_text = response.text().await?;
            return Err(format!("Gemini API Error: {}", error_text).into());
        }

        let json_resp: Value = response.json().await?;

        // Traverse the Gemini response payload
        let text_response = json_resp["candidates"][0]["content"]["parts"][0]["text"]
            .as_str()
            .ok_or("Failed to extract text from Gemini response")?;

        // Parse the inner JSON generated by Gemini
        let insight_json: Value = serde_json::from_str(text_response)?;

        let headline = insight_json["headline"].as_str().unwrap_or("Market Anomaly").to_string();
        let analysis = insight_json["analysis"].as_str().unwrap_or("No analysis provided.").to_string();
        let sentiment = insight_json["sentiment"].as_i64().unwrap_or(50) as i32;

        Ok((headline, analysis, sentiment))
    }
}
